### ISSUE TITLE
Recipe to Migrate Miscellaneous Deprecated APIs

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#10]
- [x] boolean java.util.concurrent.atomic.AtomicBoolean.weakCompareAndSet() -> weakCompareAndSetPlain()
- [x] boolean java.util.concurrent.atomic.AtomicInteger.weakCompareAndSet() -> weakCompareAndSetPlain()
- [x] boolean java.util.concurrent.atomic.AtomicIntegerArray.weakCompareAndSet() -> weakCompareAndSetPlain()
- [x] boolean java.util.concurrent.atomic.AtomicLong.weakCompareAndSet() -> weakCompareAndSetPlain()
- [x] boolean java.util.concurrent.atomic.AtomicLongArray.weakCompareAndSet() -> weakCompareAndSetPlain()
- [x] boolean java.util.concurrent.atomic.AtomicReference.weakCompareAndSet() -> weakCompareAndSetPlain()
- [x] boolean java.util.concurrent.atomic.AtomicReferenceArray.weakCompareAndSet() -> weakCompareAndSetPlain()

Low priority:
- [ ] class java.util.jar.Pack200 // add comment for removal?
- [ ] interface java.util.jar.Pack200.Unpacker // add comment for removal?
- [ ] interface java.util.jar.Pack200.Packer // add comment for removal?
- [ ] javax.tools.ToolProvider.getSystemToolClassLoader() -> Mark with a note to use `getSystemTool`instead // add comment for removal?

Defer until later. There are either no direct replacements or the changes are tricky to implement.
- [ ] java.util.jar.Attributes.Name.EXTENSION_INSTALLATION // No direct replacement, since the feature is unsupported.
- [ ] java.util.jar.Attributes.Name.IMPLEMENTATION_VENDOR_ID // No direct replacement, since the feature is unsupported.
- [ ] java.util.jar.Attributes.Name.IMPLEMENTATION_URL // No direct replacement, since the feature is unsupported.
- [ ] boolean java.lang.reflect.AccessibleObject.isAccessible() -> canAccess() // Unsafe. The replacement is @CallerSensitive. There are significant changes between isAccessible and canAcceess.
- [ ] class javax.accessibility.AccessibleResourceBundle // No direct replacement.
- [ ] java.lang.Class java.lang.reflect.Proxy.getProxyClass(java.lang.ClassLoader,java.lang.Class[]) -> See JavaDocs // Technically, this is doable, but fairly risky and will take time. Defer until users request support for this feature.
- [ ] javax.imageio.spi.ImageReaderSpi.STANDARD_INPUT_TYPE -> See JavaDocs // Defer until users request support for this feature.
- [ ] javax.imageio.spi.ImageWriterSpi.STANDARD_OUTPUT_TYPE -> See JavaDocs // Defer until users request support for this feature.

**Comment by traceyyoshima** [comment]
Closing issue - the remaining items are either tricky, not possible, or are mostly cosmetic. Will reopen issues based on user input.
