### ISSUE TITLE
Guava `com.google.common.base.Charsets` to `StandardCharsets`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#101]
See : https://guava.dev/releases/20.0/api/docs/com/google/common/base/Charsets.html

Also #100 and https://github.com/openrewrite/rewrite/issues/1724

**Comment by pway99** [comment]
for reference https://github.com/openrewrite/rewrite-migrate-java/blob/79cb372588e62db20380a5f82052cbbad771201f/src/main/resources/META-INF/rewrite/apache-commons-io.yml#L45

**Comment by tobli** [comment]
I believe this is already covered by [org.openrewrite.java.migrate.guava.PreferJavaNioCharsetStandardCharsets](https://github.com/openrewrite/rewrite-migrate-java/blob/644084b476a276ce3fe4f3b6ecf1c1549200a727/src/main/resources/META-INF/rewrite/no-guava.yml#L94)

**Comment by timtebeek** [comment]
Indeed; thanks for pointing that out! Fixed in
- https://github.com/openrewrite/rewrite-migrate-java/pull/232
