### ISSUE TITLE
Expand upgrade to Java 17 with wrappers & gradle Jaxb dependencies

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-migrate-java#109]
Might not even need much to start out, as there are few required changes.
Any language feature migrations can be adopted gradually later.

There are some required changes however, depending on the build tool.

For Maven:
1. Set source and target version to 17, [similar to java-version-11.yml](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/resources/META-INF/rewrite/java-version-11.yml)
2. Possibly [upgrade Maven wrapper](https://github.com/openrewrite/rewrite/issues/1565)
3. ~[add `.mvn/jvm.config`](https://docs.openrewrite.org/getting-started/getting-started#running-on-jdk-16-and-newer) to support running on Java 16+~

For Gradle
1. Set sourceCompatibility and targetCompatibility to 17 (through constant, preferably)
2. [Upgrade Gradle to 7.3](https://docs.gradle.org/current/userguide/compatibility.html); [via wrapper](https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java)
3. ~[add `gradle.properties`](https://docs.openrewrite.org/getting-started/getting-started#running-on-jdk-16-and-newer) to support running on Java 16+~
4. Possibly still add Java 11 jaxb dependencies, [only seen for Maven](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/resources/META-INF/rewrite/add-jaxb-dependencies.yml)

**Comment by murdos** [comment]
NB: for Maven, JVM config won't be necessary anymore with next rewrite release 💪

**Comment by timtebeek** [comment]
Maven 1. has been tackled in https://github.com/openrewrite/rewrite-migrate-java/commit/090844a13503cd621fa24fb4a8cc1f7953da280e.

**Comment by timtebeek** [comment]
Closing this issue as mostly resolved since in various changes since.
