### ISSUE TITLE
Recipe to Migrate Deprecated AWT/Swing  APIs

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#11]
These items will only impact Java Desktop applications. Each item in this list (extracted from jdeprscan) should be evaluated to cost development effort.

- [ ] javax.swing.table.TableColumn.resizedPostingDisableCount
- [ ] void javax.swing.table.TableColumn.disableResizedPosting()
- [ ] void javax.swing.table.TableColumn.enableResizedPosting
- [ ] java.lang.String javax.swing.AbstractButton.getLabel()
- [ ] void javax.swing.AbstractButton.setLabel(java.lang.String)
- [ ] void javax.swing.FocusManager.disableSwingFocusManager()
- [ ] boolean javax.swing.FocusManager.isFocusManagerEnabled()
- [ ] javax.swing.ImageIcon.component
- [ ] javax.swing.ImageIcon.tracker
- [ ] boolean javax.swing.InputVerifier.shouldYieldFocus(javax.swing.JComponent)
- [ ] class javax.swing.JApplet
- [ ] class javax.swing.JComponent.AccessibleJComponent.AccessibleFocusHandler
- [ ] javax.swing.JComponent.AccessibleJComponent.accessibleFocusHandler
- [ ] boolean javax.swing.JComponent.isManagingFocus()
- [ ] void javax.swing.JComponent.setNextFocusableComponent(java.awt.Component)
- [ ] java.awt.Component javax.swing.JComponent.getNextFocusableComponent()
- [ ] boolean javax.swing.JComponent.requestDefaultFocus()
- [ ] void javax.swing.JComponent.enable()
- [ ] void javax.swing.JComponent.disable()
- [ ] void javax.swing.JComponent.reshape(int,int,int,int)
- [ ] void javax.swing.JComponent.hide()
- [ ] javax.swing.JMenuBar javax.swing.JInternalFrame.getMenuBar()
- [ ] void javax.swing.JInternalFrame.setMenuBar(javax.swing.JMenuBar)
- [ ] java.lang.Object[] javax.swing.JList.getSelectedValues()
- [ ] java.awt.Component javax.swing.JMenuBar.getComponentAtIndex(int)
- [ ] java.lang.String javax.swing.JPasswordField.getText()
- [ ] java.lang.String javax.swing.JPasswordField.getText(int,int)
- [ ] java.awt.Component javax.swing.JPopupMenu.getComponentAtIndex(int)
- [ ] void javax.swing.JRootPane.setMenuBar(javax.swing.JMenuBar)
- [ ] javax.swing.JMenuBar javax.swing.JRootPane.getMenuBar()
- [ ] javax.swing.JScrollPane javax.swing.JTable.createScrollPaneForTable(javax.swing.JTable)
- [ ] void javax.swing.JTable.sizeColumnsToFit(boolean)
- [ ] javax.swing.JViewport.backingStore
- [ ] boolean javax.swing.JViewport.isBackingStoreEnabled()
- [ ] void javax.swing.JViewport.setBackingStoreEnabled(boolean)
- [ ] javax.swing.KeyStroke javax.swing.KeyStroke.getKeyStroke(char,boolean)
- [ ] void javax.swing.RepaintManager.addDirtyRegion(java.applet.Applet,int,int,int,int)
- [ ] java.awt.Rectangle javax.swing.ScrollPaneLayout.getViewportBorderBounds(javax.swing.JScrollPane)
- [ ] java.awt.Component javax.swing.SwingUtilities.findFocusOwner(java.awt.Component)
- [ ] void javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(java.util.Vector,javax.swing.tree.TreePath)
- [ ] class javax.swing.text.DefaultTextUI
- [ ] java.awt.Rectangle javax.swing.text.JTextComponent.modelToView(int)
- [ ] int javax.swing.text.JTextComponent.viewToModel(java.awt.Point)
- [ ] java.awt.FontMetrics javax.swing.text.LabelView.getFontMetrics()
- [ ] int javax.swing.text.PasswordView.drawUnselectedText(java.awt.Graphics,int,int,int,int)
- [ ] int javax.swing.text.PasswordView.drawSelectedText(java.awt.Graphics,int,int,int,int)
- [ ] int javax.swing.text.PasswordView.drawEchoCharacter(java.awt.Graphics,int,int,char)
- [ ] void javax.swing.text.PlainView.drawLine(int,java.awt.Graphics,int,int)
- [ ] int javax.swing.text.PlainView.drawUnselectedText(java.awt.Graphics,int,int,int,int)
- [ ] int javax.swing.text.PlainView.drawSelectedText(java.awt.Graphics,int,int,int,int)
- [ ] class javax.swing.text.TableView.TableCell
- [ ] javax.swing.text.TableView.TableCell javax.swing.text.TableView.createTableCell(javax.swing.text.Element)
- [ ] int javax.swing.text.Utilities.drawTabbedText( javax.swing.text.Segment,int,int,java.awt.Graphics,javax.swing.text.TabExpander,int)
- [ ] int javax.swing.text.Utilities.getTabbedTextWidth( javax.swing.text.Segment,java.awt.FontMetrics,int,javax.swing.text.TabExpander,int)
- [ ] int javax.swing.text.Utilities.getTabbedTextOffset( javax.swing.text.Segment,java.awt.FontMetrics,int,int,javax.swing.text.TabExpander,int)
- [ ] int javax.swing.text.Utilities.getTabbedTextOffset( javax.swing.text.Segment,java.awt.FontMetrics,int,int,javax.swing.text.TabExpander,int,boolean)
- [ ] int javax.swing.text.Utilities.getBreakLocation( javax.swing.text.Segment,java.awt.FontMetrics,int,int,javax.swing.text.TabExpander,int)
- [ ] int javax.swing.text.Utilities.getPositionAbove(javax.swing.text.JTextComponent,int,int)
- [ ] int javax.swing.text.Utilities.getPositionBelow(javax.swing.text.JTextComponent,int,int)
- [ ] java.awt.Shape javax.swing.text.View.modelToView(int,java.awt.Shape)
- [ ] int javax.swing.text.View.viewToModel(float,float,java.awt.Shape)
- [ ] void javax.swing.text.WrappedPlainView.drawLine(int,int,java.awt.Graphics,int,int)
- [ ] int javax.swing.text.WrappedPlainView.drawUnselectedText(java.awt.Graphics,int,int,int,int)
- [ ] int javax.swing.text.WrappedPlainView.drawSelectedText(java.awt.Graphics,int,int,int,int)
- [ ] java.awt.event.InputEvent.SHIFT_MASK
- [ ] java.awt.event.InputEvent.CTRL_MASK
- [ ] java.awt.event.InputEvent.META_MASK
- [ ] java.awt.event.InputEvent.ALT_MASK
- [ ] java.awt.event.InputEvent.ALT_GRAPH_MASK
- [ ] java.awt.event.InputEvent.BUTTON1_MASK
- [ ] java.awt.event.InputEvent.BUTTON2_MASK
- [ ] java.awt.event.InputEvent.BUTTON3_MASK
- [ ] int java.awt.event.InputEvent.getModifiers()
- [ ] java.awt.event.KeyEvent(java.awt.Component,int,long,int,int)
- [ ] void java.awt.event.KeyEvent.setModifiers(int)
- [ ] java.lang.String java.awt.event.KeyEvent.getKeyModifiersText(int)
- [ ] javax.naming.Context.APPLET
- [ ] javax.swing.plaf.basic.BasicDesktopPaneUI.minimizeKey
- [ ] javax.swing.plaf.basic.BasicDesktopPaneUI.maximizeKey
- [ ] javax.swing.plaf.basic.BasicDesktopPaneUI.closeKey
- [ ] javax.swing.plaf.basic.BasicDesktopPaneUI.navigateKey
- [ ] javax.swing.plaf.basic.BasicDesktopPaneUI.navigateKey2
- [ ] javax.swing.plaf.basic.BasicInternalFrameUI.openMenuKey
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.upKey
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.downKey
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.leftKey
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.rightKey
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.homeKey
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.endKey
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.dividerResizeToggleKey
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.keyboardUpLeftListener
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.keyboardDownRightListener
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.keyboardHomeListener
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.keyboardEndListener
- [ ] javax.swing.plaf.basic.BasicSplitPaneUI.keyboardResizeToggleListener
- [ ] java.awt.event.ActionListener javax.swing.plaf.basic.BasicSplitPaneUI.createKeyboardUpLeftListener()
- [ ] java.awt.event.ActionListener javax.swing.plaf.basic.BasicSplitPaneUI.createKeyboardDownRightListener()
- [ ] java.awt.event.ActionListener javax.swing.plaf.basic.BasicSplitPaneUI.createKeyboardHomeListener()
- [ ] java.awt.event.ActionListener javax.swing.plaf.basic.BasicSplitPaneUI.createKeyboardEndListener()
- [ ] java.awt.event.ActionListener javax.swing.plaf.basic.BasicSplitPaneUI.createKeyboardResizeToggleListener()
- [ ] int javax.swing.plaf.basic.BasicSplitPaneUI.getDividerBorderSize()
- [ ] javax.swing.plaf.basic.BasicTabbedPaneUI.upKey
- [ ] javax.swing.plaf.basic.BasicTabbedPaneUI.downKey
- [ ] javax.swing.plaf.basic.BasicTabbedPaneUI.leftKey
- [ ] javax.swing.plaf.basic.BasicTabbedPaneUI.rightKey
- [ ] java.awt.Rectangle javax.swing.plaf.basic.BasicTextUI.modelToView(javax.swing.text.JTextComponent,int)
- [ ] java.awt.Rectangle javax.swing.plaf.basic.BasicTextUI.modelToView(javax.swing.text.JTextComponent,int,javax.swing.text.Position.Bias)
- [ ] int javax.swing.plaf.basic.BasicTextUI.viewToModel(javax.swing.text.JTextComponent,java.awt.Point)
- [ ] int javax.swing.plaf.basic.BasicTextUI.viewToModel(javax.swing.text.JTextComponent,java.awt.Point,javax.swing.text.Position.Bias[])
- [ ] javax.swing.plaf.basic.BasicToolBarUI.upKey
- [ ] javax.swing.plaf.basic.BasicToolBarUI.downKey
- [ ] javax.swing.plaf.basic.BasicToolBarUI.leftKey
- [ ] javax.swing.plaf.basic.BasicToolBarUI.rightKey
- [ ] java.awt.AWTEvent(java.awt.Event)
- [ ] void java.awt.AWTKeyStroke.registerSubclass(java.lang.Class)
- [ ] void java.awt.BorderLayout.addLayoutComponent(java.lang.String,java.awt.Component)
- [ ] void java.awt.CardLayout.addLayoutComponent(java.lang.String,java.awt.Component)
- [ ] java.awt.Checkbox java.awt.CheckboxGroup.getCurrent()
- [ ] void java.awt.CheckboxGroup.setCurrent(java.awt.Checkbox)
- [ ] int java.awt.Choice.countItems()
- [ ] void java.awt.Component.enable()
- [ ] void java.awt.Component.enable(boolean)
- [ ] void java.awt.Component.disable()
- [ ] void java.awt.Component.show()
- [ ] void java.awt.Component.show(boolean)
- [ ] void java.awt.Component.hide()
- [ ] java.awt.Point java.awt.Component.location()
- [ ] void java.awt.Component.move(int,int)
- [ ] java.awt.Dimension java.awt.Component.size()
- [ ] void java.awt.Component.resize(int,int)
- [ ] void java.awt.Component.resize(java.awt.Dimension)
- [ ] java.awt.Rectangle java.awt.Component.bounds()
- [ ] void java.awt.Component.reshape(int,int,int,int)
- [ ] java.awt.Dimension java.awt.Component.preferredSize()
- [ ] java.awt.Dimension java.awt.Component.minimumSize()
- [ ] void java.awt.Component.layout()
- [ ] boolean java.awt.Component.inside(int,int)
- [ ] java.awt.Component java.awt.Component.locate(int,int)
- [ ] void java.awt.Component.deliverEvent(java.awt.Event)
- [ ] boolean java.awt.Component.postEvent(java.awt.Event)
- [ ] boolean java.awt.Component.handleEvent(java.awt.Event)
- [ ] boolean java.awt.Component.mouseDown(java.awt.Event,int,int)
- [ ] boolean java.awt.Component.mouseDrag(java.awt.Event,int,int)
- [ ] boolean java.awt.Component.mouseUp(java.awt.Event,int,int)
- [ ] boolean java.awt.Component.mouseMove(java.awt.Event,int,int)
- [ ] boolean java.awt.Component.mouseEnter(java.awt.Event,int,int)
- [ ] boolean java.awt.Component.mouseExit(java.awt.Event,int,int)
- [ ] boolean java.awt.Component.keyDown(java.awt.Event,int)
- [ ] boolean java.awt.Component.keyUp(java.awt.Event,int)
- [ ] boolean java.awt.Component.action(java.awt.Event,java.lang.Object)
- [ ] boolean java.awt.Component.gotFocus(java.awt.Event,java.lang.Object)
- [ ] boolean java.awt.Component.lostFocus(java.awt.Event,java.lang.Object)
- [ ] boolean java.awt.Component.isFocusTraversable()
- [ ] void java.awt.Component.nextFocus()
- [ ] java.awt.ComponentOrientation java.awt.ComponentOrientation.getOrientation(java.util.ResourceBundle)
- [ ] int java.awt.Container.countComponents()
- [ ] java.awt.Insets java.awt.Container.insets()
- [ ] void java.awt.Container.layout()
- [ ] java.awt.Dimension java.awt.Container.preferredSize()
- [ ] java.awt.Dimension java.awt.Container.minimumSize()
- [ ] void java.awt.Container.deliverEvent(java.awt.Event)
- [ ] java.awt.Component java.awt.Container.locate(int,int)
- [ ] java.awt.Cursor.predefined
- [ ] void java.awt.Dialog.show()
- [ ] void java.awt.Dialog.hide()
- [ ] class java.awt.Event
- [ ] int java.awt.FontMetrics.getMaxDecent()
- [ ] java.awt.Frame.DEFAULT_CURSOR
- [ ] java.awt.Frame.CROSSHAIR_CURSOR
- [ ] java.awt.Frame.TEXT_CURSOR
- [ ] java.awt.Frame.WAIT_CURSOR
- [ ] java.awt.Frame.SW_RESIZE_CURSOR
- [ ] java.awt.Frame.SE_RESIZE_CURSOR
- [ ] java.awt.Frame.NW_RESIZE_CURSOR
- [ ] java.awt.Frame.NE_RESIZE_CURSOR
- [ ] java.awt.Frame.N_RESIZE_CURSOR
- [ ] java.awt.Frame.S_RESIZE_CURSOR
- [ ] java.awt.Frame.W_RESIZE_CURSOR
- [ ] java.awt.Frame.E_RESIZE_CURSOR
- [ ] java.awt.Frame.HAND_CURSOR
- [ ] java.awt.Frame.MOVE_CURSOR
- [ ] void java.awt.Frame.setCursor(int)
- [ ] int java.awt.Frame.getCursorType()
- [ ] void java.awt.Graphics.finalize()
- [ ] java.awt.Rectangle java.awt.Graphics.getClipRect()
- [ ] int java.awt.List.countItems()
- [ ] void java.awt.List.addItem(java.lang.String)
- [ ] void java.awt.List.addItem(java.lang.String,int)
- [ ] void java.awt.List.clear()
- [ ] void java.awt.List.delItem(int)
- [ ] boolean java.awt.List.isSelected(int)
- [ ] boolean java.awt.List.allowsMultipleSelections()
- [ ] void java.awt.List.setMultipleSelections(boolean)
- [ ] java.awt.Dimension java.awt.List.preferredSize(int)
- [ ] java.awt.Dimension java.awt.List.preferredSize()
- [ ] java.awt.Dimension java.awt.List.minimumSize(int)
- [ ] java.awt.Dimension java.awt.List.minimumSize()
- [ ] void java.awt.List.delItems(int,int)
- [ ] int java.awt.Menu.countItems()
- [ ] int java.awt.MenuBar.countMenus()
- [ ] boolean java.awt.MenuComponent.postEvent(java.awt.Event)
- [ ] boolean java.awt.MenuContainer.postEvent(java.awt.Event)
- [ ] void java.awt.MenuItem.enable()
- [ ] void java.awt.MenuItem.enable(boolean)
- [ ] void java.awt.MenuItem.disable()
- [ ] java.awt.Rectangle java.awt.Polygon.getBoundingBox()
- [ ] boolean java.awt.Polygon.inside(int,int)
- [ ] void java.awt.PrintJob.finalize()
- [ ] void java.awt.Rectangle.reshape(int,int,int,int)
- [ ] void java.awt.Rectangle.move(int,int)
- [ ] void java.awt.Rectangle.resize(int,int)
- [ ] boolean java.awt.Rectangle.inside(int,int)
- [ ] void java.awt.ScrollPane.layout()
- [ ] int java.awt.Scrollbar.getVisible()
- [ ] void java.awt.Scrollbar.setLineIncrement(int)
- [ ] int java.awt.Scrollbar.getLineIncrement()
- [ ] void java.awt.Scrollbar.setPageIncrement(int)
- [ ] int java.awt.Scrollbar.getPageIncrement()
- [ ] void java.awt.TextArea.insertText(java.lang.String,int)
- [ ] void java.awt.TextArea.appendText(java.lang.String)
- [ ] void java.awt.TextArea.replaceText(java.lang.String,int,int)
- [ ] java.awt.Dimension java.awt.TextArea.preferredSize(int,int)
- [ ] java.awt.Dimension java.awt.TextArea.preferredSize()
- [ ] java.awt.Dimension java.awt.TextArea.minimumSize(int,int)
- [ ] java.awt.Dimension java.awt.TextArea.minimumSize()
- [ ] void java.awt.TextField.setEchoCharacter(char)
- [ ] java.awt.Dimension java.awt.TextField.preferredSize(int)
- [ ] java.awt.Dimension java.awt.TextField.preferredSize()
- [ ] java.awt.Dimension java.awt.TextField.minimumSize(int)
- [ ] java.awt.Dimension java.awt.TextField.minimumSize()
- [ ] java.lang.String[] java.awt.Toolkit.getFontList()
- [ ] java.awt.FontMetrics java.awt.Toolkit.getFontMetrics(java.awt.Font)
- [ ] int java.awt.Toolkit.getMenuShortcutKeyMask()
- [ ] void java.awt.Window.reshape(int,int,int,int)
- [ ] void java.awt.Window.show()
- [ ] void java.awt.Window.hide()
- [ ] boolean java.awt.Window.postEvent(java.awt.Event)
- [ ] void java.awt.Window.applyResourceBundle(java.util.ResourceBundle)
- [ ] void java.awt.Window.applyResourceBundle(java.lang.String)
- [ ] javax.swing.text.html.FormView.SUBMIT
- [ ] javax.swing.text.html.FormView.RESET
- [ ] void javax.swing.text.html.HTMLEditorKit.InsertHTMLTextAction.insertAtBoundry()
- [ ] void java.awt.image.renderable.RenderContext.preConcetenateTransform(java.awt.geom.AffineTransform)
- [ ] void java.awt.image.renderable.RenderContext.concetenateTransform(java.awt.geom.AffineTransform)
- [ ] java.awt.datatransfer.DataFlavor.plainTextFlavor
- [ ] boolean java.awt.datatransfer.DataFlavor.equals(java.lang.String)
- [ ] java.lang.String java.awt.datatransfer.DataFlavor.normalizeMimeTypeParameter(java.lang.String,java.lang.String)
- [ ] java.lang.String java.awt.datatransfer.DataFlavor.normalizeMimeType(java.lang.String)
- [ ] class javax.swing.plaf.metal.MetalComboBoxUI.MetalComboPopup
- [ ] void javax.swing.plaf.metal.MetalComboBoxUI.editablePropertyChanged(java.beans.PropertyChangeEvent)
- [ ] void javax.swing.plaf.metal.MetalComboBoxUI.removeListeners()
- [ ] class javax.swing.plaf.metal.MetalFileChooserUI.FileRenderer
- [ ] class javax.swing.plaf.metal.MetalFileChooserUI.SingleClickListener
- [ ] void javax.swing.plaf.metal.MetalScrollPaneUI.uninstallListeners(javax.swing.JScrollPane)
- [ ] java.awt.Rectangle javax.swing.plaf.multi.MultiTextUI.modelToView(javax.swing.text.JTextComponent,int)
- [ ] java.awt.Rectangle javax.swing.plaf.multi.MultiTextUI.modelToView(javax.swing.text.JTextComponent,int,javax.swing.text.Position.Bias)
- [ ] int javax.swing.plaf.multi.MultiTextUI.viewToModel(javax.swing.text.JTextComponent,java.awt.Point)
- [ ] int javax.swing.plaf.multi.MultiTextUI.viewToModel(javax.swing.text.JTextComponent,java.awt.Point,javax.swing.text.Position.Bias[])

**Comment by tkvangorder** [comment]
Closing this issue, as we do not have a lot of interest in migrating UI/Desktop apps from Java 8 to 11. We can revisit this long list of deprecations if there is a high demand for this at a later date.

**Comment by jonico** [comment]
This was closed in 2021 with "we can revisit this long list of deprecations if there is a high demand for this at a later date" — so, purely as a data point in case demand is being tracked, plus a workaround for anyone who lands here from a search.

I've just migrated a 2006 Swing/JDBC desktop application (a German Kindergarten card-index app, recovered from SourceForge CVS) from Java 8 to Java 21. `UpgradeToJava21` handled almost everything. Of the 10 deprecation warnings the JDK 21 compiler flagged, **4 were `Window.show()` / `Dialog.show()`** — the single largest category, and the only one with no recipe coverage.

Interestingly, `show()`/`hide()` on `java.awt.Window` and `java.awt.Dialog` aren't in the checklist above, which is drawn from a `javax.swing`-focused `jdeprscan` run (it has `javax.swing.JComponent.hide()` but not the AWT pair). So even if the Swing list stays out of scope, these two might be worth considering separately — they're deprecated since Java 1.5 and near-universal in pre-2010 desktop code.

Also worth noting that the module *does* already ship some AWT deprecation coverage — `ReplaceAWTGetPeerMethod` and `ReplaceComSunAWTUtilitiesMethods` — so this wouldn't be opening a new area so much as filling a gap in one that partially exists.

## Workaround

It composes cleanly from existing recipes, so no new code is needed to use it today:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.example.MigrateDeprecatedAwtShow
displayName: Replace deprecated Window/Dialog show() with setVisible(true)
recipeList:
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: java.awt.Window show()
      newMethodName: setVisible
      matchOverrides: true
  - org.openrewrite.java.AddLiteralMethodArgument:
      methodPattern: java.awt.Window setVisible()
      argumentIndex: 0
      literal: true
      primitiveType: boolean
  - org.openrewrite.java.AddLiteralMethodArgument:
      methodPattern: java.awt.Dialog setVisible()
      argumentIndex: 0
      literal: true
      primitiveType: boolean
```

The transformation is behaviour-preserving: `Component.setVisible(true)` dispatches straight back into `Window.show()` / `Dialog.show()`, so validation and modal blocking are unchanged.

Two things I ran into building that, in case they're useful:

- `ChangeMethodName` with `matchOverrides: true` on `java.awt.Window show()` does correctly reach `java.awt.Dialog.show()`.
- `AddLiteralMethodArgument` has no `matchOverrides` option, so the two `setVisible()` patterns have to be listed separately. Not a problem, just slightly surprising given the asymmetry with `ChangeMethodName`.

No expectation that this reopens anything — the 2021 reasoning still makes sense, and desktop Java is a niche. Just adding evidence to the pile, since Java 8 desktop apps are now facing 8→21/25 jumps rather than 8→11. Happy to contribute a recipe + tests if it ever becomes wanted.
