### ISSUE TITLE
Issue discovered with `src/main/java/com/google/cloud/tools/maven/endpoints/framework/EndpointsGenSrcMojo.java`

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite-migrate-java#117]
### Problem

An import was added but the code was not otherwise changed
  
  ### Expected behavior

The import shouldn't have change without the change happening elsewhere in the code to replace the violating method call.
  
  ### Example diff
  
  
  ```diff
   import java.io.File;
 import java.io.FileFilter;
 import java.io.IOException;
+import java.nio.file.Files;
 import java.nio.file.StandardCopyOption;
 import java.util.ArrayList;
 import java.util.Arrays;
  ```
  
  
  #### Recipes in example diff:
  - org.openrewrite.java.migrate.guava.NoGuavaCreateTempDir
  
  ### References:
  - Recipe ID: `undefined`
  - Recipe Name: "Use `Files#createTempDirectory()` instead of Guava"
  - Repository: GoogleCloudPlatform/endpoints-framework-maven-plugin/master
  - Created at Mon Aug 08 2022 19:35:50 GMT-0700 (Pacific Daylight Time)

**Comment by timtebeek** [comment]
I'm going to close this issue as the underlying repository has been archived, and I've not seen any other reports.
> This repository has been archived by the owner on Nov 14, 2022. It is now read-only.
