### ISSUE TITLE
Recipe to Migrate Deprecated JMX/Management APIs

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#12]
- [x] void javax.management.monitor.CounterMonitor.setThreshold(java.lang.Number) // Doable.

Most of the remaining items require understanding how the interfaces/abstract classes were implemented. Otherwise, there are API changes aren't things that we can infer without more information, and/or would require a significant amount of time to implement.

The items without comments require contextual understanding of the code base to replace the deprecations safely.
- [ ] void javax.management.monitor.CounterMonitorMBean.setThreshold(java.lang.Number)
- [ ] void javax.management.monitor.Monitor.setObservedObject(javax.management.ObjectName)
- [ ] class javax.management.DefaultLoaderRepository
- [ ] class javax.management.loading.DefaultLoaderRepository
- [ ] javax.management.openmbean.OpenType.ALLOWED_CLASSNAMES 
- [ ] javax.management.remote.rmi.RMIConnectorServer.CREDENTIAL_TYPES  
- [ ] void javax.management.AttributeValueExp.setMBeanServer(javax.management.MBeanServer) // method literally does nothing, so it's safe to remove, but the complexity depends on how it is used.
- [ ] void javax.management.StringValueExp.setMBeanServer(javax.management.MBeanServer) // method literally does nothing, so it's safe to remove, but the complexity depends on how it is used.
- [ ] javax.management.AttributeValueExp() 
- [ ] java.lang.Number javax.management.monitor.CounterMonitor.getDerivedGauge() 
- [ ] long javax.management.monitor.CounterMonitor.getDerivedGaugeTimeStamp()
- [ ] java.lang.Number javax.management.monitor.CounterMonitor.getThreshold()
- [ ] java.lang.Number javax.management.monitor.CounterMonitorMBean.getDerivedGauge()
- [ ] long javax.management.monitor.CounterMonitorMBean.getDerivedGaugeTimeStamp()
- [ ] java.lang.Number javax.management.monitor.CounterMonitorMBean.getThreshold()
- [ ] java.lang.Number javax.management.monitor.GaugeMonitor.getDerivedGauge()
- [ ] long javax.management.monitor.GaugeMonitor.getDerivedGaugeTimeStamp()
- [ ] java.lang.Number javax.management.monitor.GaugeMonitorMBean.getDerivedGauge()
- [ ] java.lang.String javax.management.monitor.StringMonitor.getDerivedGauge()
- [ ] long javax.management.monitor.StringMonitor.getDerivedGaugeTimeStamp()
- [ ] java.lang.String javax.management.monitor.StringMonitorMBean.getDerivedGauge()
- [ ] long javax.management.monitor.GaugeMonitorMBean.getDerivedGaugeTimeStamp()
- [ ] long javax.management.monitor.StringMonitorMBean.getDerivedGaugeTimeStamp()
- [ ] void javax.management.ValueExp.setMBeanServer(javax.management.MBeanServer)
- [ ] javax.management.monitor.Monitor.dbgTag // No replacement exists.
- [ ] class javax.management.remote.rmi.RMIIIOPServerImpl // No replacement exists.
- [ ] javax.management.monitor.Monitor.alreadyNotified // possible, but might be tricky.
- [ ] java.io.ObjectInputStream javax.management.MBeanServer.deserialize(javax.management.ObjectName,byte[]) // throws UnsupportedOperationException.
- [ ] java.io.ObjectInputStream javax.management.MBeanServer.deserialize(java.lang.String,byte[]) // throws UnsupportedOperationException.
- [ ] java.io.ObjectInputStream javax.management.MBeanServer.deserialize(java.lang.String,javax.management.ObjectName,byte[]) // throws UnsupportedOperationException.
- [ ] javax.management.ObjectName javax.management.monitor.Monitor.getObservedObject() // complex to do right.
- [ ] javax.management.ObjectName javax.management.monitor.MonitorMBean.getObservedObject() // complex to do right.
- [ ] void javax.management.monitor.MonitorMBean.setObservedObject(javax.management.ObjectName) // complex to do right.

**Comment by traceyyoshima** [comment]
Added comments to the issues. The majority of the remaining items are not possible without being aware of how abstract classes or interfaces are implemented. There are a few that may be doable, but would require a significant time investment to replace the deprecations without breaking things.
