### ISSUE TITLE
Recipe to Migrate Deprecated `java.lang` and  `java.io` APIs

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#13]
### **Deprecated in Java 8:**
- [x] boolean java.lang.Character.isJavaLetter(char) -> isJavaIdentifierStart()
- [x] boolean java.lang.Character.isJavaLetterOrDigit(char) -> isJavaIdentifierPart()
- [x] boolean java.lang.Character.isSpace(char) -> isWhitespace()

### **Deprecated in Java 1.1:**
**Tricky:**
_Notes about java.util.Date: The default constructor uses the JVM default time zone and starts at the beginning of the day. So the result may very based on where, when and what default time zone is. The java recommended replacement is Calendar, but there is a high cost to Calendar.newInstance. So, it's generally recommended to use either java.time or joda-time._
- [ ] java.util.Date(int,int,int)
- [ ] java.util.Date(int,int,int,int,int)
- [ ] java.util.Date(int,int,int,int,int,int)
- [ ] java.util.Date(java.lang.String)
- [ ] long java.util.Date.UTC(int,int,int,int,int,int)
- [ ] long java.util.Date.parse(java.lang.String)
- [ ] int java.util.Date.getYear()
- [ ] void java.util.Date.setYear(int)
- [ ] int java.util.Date.getMonth()
- [ ] void java.util.Date.setMonth(int)
- [ ] int java.util.Date.getDate()
- [ ] void java.util.Date.setDate(int)
- [ ] int java.util.Date.getDay()
- [ ] int java.util.Date.getHours()
- [ ] void java.util.Date.setHours(int)
- [ ] int java.util.Date.getMinutes()
- [ ] void java.util.Date.setMinutes(int)
- [ ] int java.util.Date.getSeconds()
- [ ] void java.util.Date.setSeconds(int)
- [ ] java.lang.String java.util.Date.toLocaleString()
- [ ] java.lang.String java.util.Date.toGMTString()
- [ ] int java.util.Date.getTimezoneOffset()

### **Deprecated in Java 9:**
- [ ] class java.util.Observable // Tricky to fix.
- [ ] interface java.util.Observer // Tricky to fix.

### **Deprecated in Java 10:**
- [x] java.lang.Class.newInstance() -> getDeclaredConstructor().newInstance()
- [x] int java.lang.Runtime.Version.major() -> feature()
- [x] int java.lang.Runtime.Version.minor() -> interim()
- [x] int java.lang.Runtime.Version.security() -> update()
- [x] void java.lang.SecurityManager.checkMulticast(java.net.InetAddress,byte) -> See method implementation for replacement code. // This may be pretty tricky.
- [x] java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) -> defineClass(String,byte[],int,int) // Requires imperative to add an additional argument. The `String` may be passed in as null, which matches what the deprecated method would do.

**Low Priority:**
- [ ] class java.lang.Compiler -> Add a TODO comment to remove this
- [ ] int java.lang.Thread.countStackFrames() -> "Remove this call" marker?
- [ ] void java.lang.Runtime.traceInstructions(boolean) -> Mark as not implemented.
- [ ] void java.lang.Runtime.traceMethodCalls(boolean) -> Mark as not implemented.
- [ ] void java.lang.Thread.stop() -> "Remove this call, reference https://docs.oracle.com/javase/8/docs/technotes/guides/concurrency/threadPrimitiveDeprecation.html"
- [ ] void java.lang.Thread.suspend() -> "Remove this call, reference https://docs.oracle.com/javase/8/docs/technotes/guides/concurrency/threadPrimitiveDeprecation.html" 
- [ ] void java.lang.Thread.resume() -> "Remove this call, reference https://docs.oracle.com/javase/8/docs/technotes/guides/concurrency/threadPrimitiveDeprecation.html"
- [ ] void java.lang.ThreadGroup.stop() -> "Remove this call, reference https://docs.oracle.com/javase/8/docs/technotes/guides/concurrency/threadPrimitiveDeprecation.html"
- [ ] void java.lang.ThreadGroup.suspend() -> "Remove this call, reference https://docs.oracle.com/javase/8/docs/technotes/guides/concurrency/threadPrimitiveDeprecation.html"
- [ ] void java.lang.ThreadGroup.resume() -> "Remove this call, reference https://docs.oracle.com/javase/8/docs/technotes/guides/concurrency/threadPrimitiveDeprecation.html"
- [ ] boolean java.lang.ThreadGroup.allowThreadSuspension(boolean) -> "Remove this call, reference https://docs.oracle.com/javase/8/docs/technotes/guides/concurrency/threadPrimitiveDeprecation.html"

**Tricky:**
- [ ] java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) -> getDefinedPackage() // Requires replacement of super.getPackage(). ClassLoader is an abstract class with a protected method getPackage.
- [ ] java.lang.Package java.lang.Package.getPackage(java.lang.String) -> ClassLoader.getDefinedPackage() // Requires a change type, and changeMethodName.
- [ ] java.net.URL java.io.File.toURL() // the recommended replacement involves creating a URI first then converting the URI into a URL. toURL throws a checked MalformedURLException, but toURI throws an unchecked URISyntaxException.
- [ ] void java.io.FileInputStream.finalize() // requires checking for subclasses that override the finalize() and code `should be modified to use alternative cleanup mechanisms and to remove the overriding`.
- [ ] java.lang.String java.io.ByteArrayOutputStream.toString(int) // The deprecation notes state `
This method does not properly convert bytes into characters` and should not be in, since it's unreliable.
- [ ] java.lang.String java.io.DataInputStream.readLine() // deprecation notes state `This method does not properly convert bytes to characters`.
- [ ] class java.io.LineNumberInputStream // deprecation notes state `This class incorrectly assumes that bytes adequately represent characters.
- [ ] java.lang.String java.io.ObjectInputStream.readLine() // deprecation notes state `This method does not properly convert bytes to characters.`
- [ ] void java.io.ObjectOutputStream.PutField.write(java.io.ObjectOutput) // deprecation notes state `This method does not write the values contained by this PutField object in a proper format, and may result in corruption of the serialization stream`. Replacement may involve significant changes.
- [ ] java.io.StreamTokenizer(java.io.InputStream) // Replacement requires converting the InputStream arg into a Reader and passing in the reader instead.
- [ ] class java.io.StringBufferInputStream. // Deprecation notes state `This class does not properly convert characters into bytes.` Requires replacing the StringBufferInputStream with a StringReader, and may require significant changes.
- [ ] void java.util.Properties.save(java.io.OutputStream,java.lang.String) // fairly simple to replace. But requires an IOException to be handled. The save() method swallows the IOException that may be thrown by store() ...

**Comment by traceyyoshima** [comment]
Closing issue - the remaining items are either tricky, not possible, or are mostly cosmetic. Will reopen issues based on user input.
