### ISSUE TITLE
Recipe to Migrate Deprecated `javax.lang.model.util` to newest versions

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#16]
These should all be migrated to version 9.

- [x] javax.lang.model.util.AbstractAnnotationValueVisitor6() -> AbstractAnnotationValueVisitor9()
- [x] javax.lang.model.util.AbstractElementVisitor6()
- [x] javax.lang.model.util.AbstractTypeVisitor6()
- [x] javax.lang.model.util.ElementKindVisitor6()
- [x] javax.lang.model.util.ElementKindVisitor6()
- [x] javax.lang.model.util.ElementScanner6()
- [x] javax.lang.model.util.ElementScanner6()
- [x] javax.lang.model.util.SimpleAnnotationValueVisitor6()
- [x] javax.lang.model.util.SimpleAnnotationValueVisitor6()
- [x] javax.lang.model.util.SimpleElementVisitor6()
- [x] javax.lang.model.util.SimpleElementVisitor6()
- [x] javax.lang.model.util.SimpleTypeVisitor6()
- [x] javax.lang.model.util.SimpleTypeVisitor6()
- [x] javax.lang.model.util.TypeKindVisitor6()
- [x] javax.lang.model.util.TypeKindVisitor6()

**Comment by traceyyoshima** [comment]
fixed in [commit](https://github.com/openrewrite/rewrite-migrate-java/commit/b589cb8d104b3de37b845daa9f46dd4bdf0e8c82)
