### ISSUE TITLE
Bug: onlyIfUsing uses array in `JavaxValidationMigrationToJakartaValidation`

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite-migrate-java#170]
Hi,

the recipe `org.openrewrite.java.migrate.jakarta.JavaxValidationMigrationToJakartaValidation` uses an array in the `AddDependency`of the recipe list. This is not supported and should be changed to the direct value.

I make a PR.

Kind regards
Thomas

**Comment by timtebeek** [comment]
Thanks again, both for the report & the quick fix!
