### ISSUE TITLE
AddJaxbDependencies - special handling for spring-boot-starter-test

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite-migrate-java#177]
(update -- carved off the duplicate dependency issue into #178)

I think it would be valuable to add special handling for `spring-boot-starter-test` to `AddJaxbDependencies`. As far as I can tell, [the xml-bind functionality is only used by the starter's transitive `xmlunit` dependency](https://github.com/spring-projects/spring-boot/pull/28344) (which provides AssertJ extensions for validating XML strings), and a large swath of projects using this starter will *not* be using that functionality.

I'd propose adding logic in `AddJaxbDependencies` to check if `jakarta.xml.bind-api` is *only* on the classpath as a transitive dependency of `spring-boot-starter-test`, and if so, add the jaxb implementation `onlyIfUsing` `org.xmlunit`. Otherwise, unconditionally add the jaxb implementation as we do now.

I think this would require retaining a bit more data in the `MavenResolutionResult`, namely, an `includedBy` list on `ResolvedPom`. I expect this can be done within the existing resolution code with minimal performance impact, and may be useful for other purposes in the future.

**Comment by timtebeek** [comment]
We've had a recent change in https://github.com/openrewrite/rewrite-migrate-java/commit/b6215379d0de1d63bcd19de5952d5edd3073b21b that limits the applicability of the recipe. I'm optimistic that closes this issue too, but feel free to reopen if you're still seeing issues.
