### ISSUE TITLE
GraphQL 20+ : Migrate from SimpleInstrumentation to SimplePerformantInstrumentation

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#189]
Migrate to `SimplePerformantInstrumentation`

```diff

-public class CustomInstrumentation extends SimpleInstrumentation {
+public class CustomInstrumentation extends SimplePerformantInstrumentation {

```

See https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/instrumentation/SimpleInstrumentation.java#L14-L17

**Comment by yeikel** [comment]
@timtebeek I don't believe we're currently supporting GraphQL and I am not sure where this would fit 

GraphQL-Java is definitely a popular framework, likely used by our other migrations

**Comment by timtebeek** [comment]
Ideally we'd see [graphql-java](https://github.com/graphql-java/graphql-java) distribute their own migration recipes, similar to what we saw [Axon adopt last week](https://www.moderne.io/blog/how-axon-framework-handles-breaking-changes-through-openrewrite). You can pitch it to them to adopt migration recipes going forward, especially for the small stuff that's easily supported with Yaml recipes. I've already [pitched the same to Apache Wicket](https://issues.apache.org/jira/projects/WICKET/issues/WICKET-7029) earlier this week, and it's something we're pushing more towards.

**Comment by yeikel** [comment]
Sure. I submitted https://github.com/graphql-java/graphql-java/issues/3108 to see what they think

**Comment by timtebeek** [comment]
Great! Let's hope they accept your suggestion; Meanwhile, or if not accepted there, you can always show them how it's done with a `rewrite.yml` in a personal repository, possibly supplemented with some custom visitors.

I'll close this issue here, but appreciate the suggestion, both here and at graphql-java!

**Comment by yeikel** [comment]
> Sure; we're working on a model where the community can provide recipes to repositories under the openrewrite GitHub organization. Perhaps you can start a GitHub repository under your own account at first for now, that we then later adopt into the openrewrite for distribution when it's closer to completion?

I am in no rush and I can wait for that to be completed. Thanks for letting me know
