### ISSUE TITLE
Recipe to Add JAX-WS Dependencies to a Maven Build

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#19]
The JAX-WS API is used for creating soap-based services and clients. This library is no longer packaged with the Java Runtime and this recipe will ensure the proper external dependencies are added to an existing Maven build.

The two dependencies that are added (if a project uses JAXB) are:

```
      groupId: jakarta.xml.ws
      artifactId: jakarta.xml.ws-api
      version: 2.3.x

      groupId: com.sun.xml.ws
      artifactId: jaxws-rt
      version: 2.3.x
```

This recipe will also remove an older artifact (javax.xml.ws:jaxws-api) as it is now superseded by the jakarta library.

**Comment by traceyyoshima** [comment]
On hold, adding the dependency is simple to do, but adding the plugin requires https://github.com/openrewrite/rewrite/issues/585.

**Comment by tkvangorder** [comment]
There is initial support for updating the jax-ws artifacts in a maven-based build.
