### ISSUE TITLE
version 1.17.2 does not show up at Maven Central

### ISSUE THREAD

**Issue by martinlippert** [openrewrite/rewrite-migrate-java#190]
Looks like publishing version `1.17.2` to Maven Central didn't succeed yet:
https://central.sonatype.com/artifact/org.openrewrite.recipe/rewrite-migrate-java/1.17.1/versions

Would be awesome if someone could double check...

**Comment by timtebeek** [comment]
Weird how that did not kick off; just recreated the tag and release and it's kicked off now:
https://github.com/openrewrite/rewrite-migrate-java/actions/runs/4372452918
Should be available shortly.
