### ISSUE TITLE
Replace `java.lang.Runtime exec(String, ..)` with `java.lang.Runtime exec(String[], ..)` or `ProcessBuilder`

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-migrate-java#193]
As per https://javaalmanac.io/jdk/20/apidiff/17/

Runtime |  
-- | --
[exec(String)](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Runtime.html#exec(java.lang.String)) | + deprecated
[exec(String, String[])](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Runtime.html#exec(java.lang.String,java.lang.String%5B%5D)) | + deprecated
[exec(String, String[], File)](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Runtime.html#exec(java.lang.String,java.lang.String%5B%5D,java.io.File)) | + deprecated

**Comment by knutwannheden** [comment]
@timtebeek I am closing this as I think this should already be covered by `org.openrewrite.java.cleanup.ReplaceDeprecatedRuntimeExecMethods` (see openrewrite/rewrite#2895) and it is in fact already part of `java-version-20.yml`. Please reopen if I missed something.

**Comment by timtebeek** [comment]
Don't know how I missed that; guess I looked in the docs rather than in source, and didn't find it there.
