### ISSUE TITLE
Remove calls to `Thread.stop()`

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-migrate-java#194]
https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Thread.html#stop()

As of Java 20 `Thread.stop()` _always_ throws `UnsupportedOperationException`(!).

> **Deprecated, for removal: This API element is subject to removal in a future version.**
This method was originally specified to "stop" a victim thread by causing the victim thread to throw a [ThreadDeath](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/ThreadDeath.html). It was inherently unsafe. Stopping a thread caused it to unlock all of the monitors that it had locked (as a natural consequence of the ThreadDeath exception propagating up the stack). If any of the objects previously protected by these monitors were in an inconsistent state, the damaged objects became visible to other threads, potentially resulting in arbitrary behavior. Usages of stop should be replaced by code that simply modifies some variable to indicate that the target thread should stop running. The target thread should check this variable regularly, and return from its run method in an orderly fashion if the variable indicates that it is to stop running. If the target thread waits for long periods (on a condition variable, for example), the interrupt method should be used to interrupt the wait. For more information, see [Why are Thread.stop, Thread.suspend and Thread.resume Deprecated?](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/doc-files/threadPrimitiveDeprecation.html).

It's already been [@Deprecated](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Deprecated.html)([since](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Deprecated.html#since())="1.2", [forRemoval](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Deprecated.html#forRemoval())=true).

From reading the above description it might be too simplistic to simply remove calls without additional guards, but leaving the calls in is guaranteed not to work past v20.

**Comment by yeikel** [comment]
@timtebeek 

Regarding this 

> From reading the above description it might be too simplistic to simply remove calls without additional guards, but leaving the calls in is guaranteed not to work past v20.

Would you accept the simplistic version that just removes it? Or are you hoping to do even more? 

If removal is the initial target, maybe I can take this one

**Comment by timtebeek** [comment]
I'd been wondering what the best course of action is here; I think merely removing the `Thread.stop()` could lead to unspecified behavior, with runaway threads that might lead to instability and hard to troubleshoot issues. Leaving it in would guarantee `UnsupportedOperationException` being thrown, which isn't much better, and also limited to runtime.

I'm even half considering making this a breaking change that the developer will have to look at in some way, for instance by inserting a comment just before `Thread.stop()` to sketch the above background, then commenting out the `Thread.stop()` and inserting some gibberish that a compiler will not accept. That at least shifts the issue from runtime to compile time, and the developer can have a look at the specific case.

What do you suppose we do in this case? We can also start with a recipe that adds a Marker to any such calls, which should help uncover this when run with the platform. It's a tricky pattern this one, with no clear best case of handling it just yet.

**Comment by timtebeek** [comment]
As a start it might make sense to do something like the following to surface problematic cases and encourage rethinking:
```java
@Test
@Issue("https://github.com/openrewrite/rewrite-migrate-java/issues/194")
@DocumentExample
void replaceWithThrows() {
    rewriteRun(
      //language=java
      java(
        """
          class Foo {
            void bar() {
                Thread.currentThread().stop();
            }
          }
          """,
        """
          class Foo {
              void bar() {
                  // `Thread.stop()` always throws a `new UnsupportedOperationException()` in Java 21+.
                  // For detailed migration instructions see the migration guide available at
                  // https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/doc-files/threadPrimitiveDeprecation.html
                  throw new UnsupportedOperationException();
              }
          }
          """

      )
    );
}
```

**Comment by timtebeek** [comment]
That implementation is now in
- https://github.com/openrewrite/rewrite-migrate-java/pull/354

We _could_ follow up with a proper replacement, but that will be a lot more work, and context dependent.

**Comment by timtebeek** [comment]
Picked up as described above ; If anyone sees an option to fully automate a complete fix they are welcome to open a pull request.
