### ISSUE TITLE
Java 8 to 11

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-migrate-java#2]
This needs to be broken down into separate issues/tasks per https://github.com/openrewrite/rewrite-migrate-java#readme. Some of these already have recipes, so let's keep track here what is done and what's outstanding.

**Comment by okundzich** [comment]
@pway99 @traceyyoshima please help triage

**Comment by tkvangorder** [comment]
Closing this as this has been divided into smaller units of work.
