### ISSUE TITLE
Recipe JavaVersion11 replaces a maven property with the number 11 in the <release> tag of the Maven-compiler-plugin.

### ISSUE THREAD

**Issue by jbessels** [openrewrite/rewrite-migrate-java#204]
We were already using Java 11 but the recipe list of 'Migrate Java 11' contained some nice recipes. Ran it. We are using Maven. I noticed that after running the recipes the <source> and <target> tags were replaced by a single<release> tag for the Java version. The value was set to 11. We are using Java properties for things like version number for the frameworks/plugins etc and also our java version. 
`<java.version>11</java.version>`
I changed the tag back to `<release>${java.version}</release> `and reran the 'Migrate java 11' recipe. After that the property was again changed back to 11. The culprit is `<recipe>org.openrewrite.java.migrate.JavaVersion11</recipe>`.  I think this is a bug. Tim told me there is an explicit check that should prevent this. **But apparently this does not seem to work in all cases.** 

Not tested it with Java 17 OR when the `<source>` and `<target>` tags in maven-compiler-plugin still exist. And ofc not only when the the property is called is  java.version but also with a different name like `<YesWeAreUsingJava11>11</YesWeAreUsingJava11>` 

![image](https://user-images.githubusercontent.com/69236284/228857143-26fb9a5a-3699-4e2e-8d48-2eb55f388e81.png)

**Comment by timtebeek** [comment]
So we do indeed have some handling; here's the above screenshot as a link: https://github.com/openrewrite/rewrite-migrate-java/blob/9a74c66bf6698dd437dedb3fcd0f74f07fe9bc03/src/main/java/org/openrewrite/java/migrate/UpgradeJavaVersion.java#L76-L90

For completeness sake: could you post a `pom.xml` snippet how you're using that `java.version` property? Within a `<release>` tag for the compiler plugin I imagine from your issue? Want to be sure there's no uncovered cases when we pick this up.

**Comment by jbessels** [comment]
Of course. The plugin resides inside a   `<pluginManagement>   <plugins>`section. 
![image](https://user-images.githubusercontent.com/69236284/228863090-f50af5da-705a-4424-900e-9f4d8ea6768f.png)

**Comment by jbessels** [comment]
Just realized you asked for a code snippet.
```
  <plugin>
                    <!-- Build with specified Java version. -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <release>${java.version}</release>
                        <compilerArgs>
                            <arg>-parameters</arg>
                        </compilerArgs>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>io.micronaut</groupId>
                                <artifactId>micronaut-inject-java</artifactId>
                                <version>${micronaut.version}</version>
                            </path>
                            <path>
                                <groupId>io.micronaut</groupId>
                                <artifactId>micronaut-validation</artifactId>
                                <version>${micronaut.version}</version>
                            </path>
                            <path>
                                <groupId>io.micronaut.openapi</groupId>
                                <artifactId>micronaut-openapi</artifactId>
                                <version>${micronaut.openapi.version}</version>
                            </path>

                            <!-- Multiple <path> tags removed so a screenshot could be taken                            -->

                            <path>
                                <groupId>io.micronaut.tracing</groupId>
                                <artifactId>micronaut-tracing-opentelemetry-annotation</artifactId>
                                <version>${micronaut-tracing-bom.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
```

**Comment by timtebeek** [comment]
We've gone through a number of iterations on this recipe since; are you still seeing the same issue? Should we keep this issue open? Or can we close this one and only reopen if it happens again with recent versions, or new versions of Java?

**Comment by melloware** [comment]
I think this is safe to close.  I have not noticed any issues in my migrations related to this.
