### ISSUE TITLE
java17 migration needs to update java.toolchain.languageVersion in build.gradle

### ISSUE THREAD

**Issue by kunli2** [openrewrite/rewrite-migrate-java#210]
java17 migration needs to update `java.toolchain.languageVersion` in `build.gradle`

example:
```
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(8)
  }
}
```

Change `8` -> `17`.

this is a good example of [repo](https://github.com/Netflix/frigga) to demo

**Comment by timtebeek** [comment]
This looks to have been tackled in https://github.com/openrewrite/rewrite-migrate-java/commit/2ca989a44b8088603a041d41eba54b41816ac21b ; build failed due to Maven Central issues; we can likely close this one when the build passes.
