### ISSUE TITLE
Problems of recipe UseJavaUtilBase64

### ISSUE THREAD

**Issue by D-D-H** [openrewrite/rewrite-migrate-java#212]
Hi team,

The following steps can reproduce the problems I encounter.

1. Generate a simple maven project
```
$ mvn archetype:generate -DgroupId=demo -DartifactId=demo -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false
```

2. Modify App.java
```
package demo;

import sun.misc.BASE64Decoder;
import sun.misc.BASE64Encoder;

public class App {

    public static void main(String[] args) {
        byte[] b = new byte[16];
        try {
            BASE64Encoder encoder = new BASE64Encoder();
            String encode = encoder.encode(b);
            new BASE64Decoder().decodeBuffer(encode);

            doSomething();

        } catch (Exception e) {
            System.out.println("Hit");
        }
    }

    static void doSomething() {
        throw new RuntimeException();
    }

}

class Base64 {

}
```

3. Add openrewrite config to pom.xml
```
  <build>
    <plugins>
      <plugin>
        <groupId>org.openrewrite.maven</groupId>
        <artifactId>rewrite-maven-plugin</artifactId>
        <version>4.40.0</version>
        <configuration>
          <activeRecipes>
            <recipe>org.openrewrite.java.migrate.UseJavaUtilBase64</recipe>
          </activeRecipes>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-migrate-java</artifactId>
            <version>1.17.0</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
```

4. run rewite
```
$ mvn rewrite:run
```

The modified result of App.java is
```
package demo;

import java.util.Base64;

public class App {

    public static void main(String[] args) {
        byte[] b = new byte[16];
        Base64.Encoder encoder = Base64.getEncoder();
        String encode = encoder.encodeToString(b);
        Base64.getDecoder().decode(encode);

        doSomething();
    }

    static void doSomething() {
        throw new RuntimeException();
    }

}

class Base64 {

}
```

There are two problems with this result.
1. The original catch statement is removed, and this will cause inconsistent behavior.
2. There is a class named Base64 in App.java, and the modified result cannot be compiled.

Another problem we faced in our internal practice is that we found an incompatible problem between java.util.Base64 and sun.misc.BASE64. Some similar discussion can be found at https://stackoverflow.com/questions/35301409/is-java-8-java-util-base64-a-drop-in-replacement-for-sun-misc-base64 .

**Comment by timtebeek** [comment]
Thank you for bringing this to our attention with such clear steps to reproduce!

**Comment by sambsnyd** [comment]
In these [two](https://github.com/openrewrite/rewrite/commit/5b964b9d4f0c1a656dcff1ac9f79d0fda1060139) [commits](https://github.com/openrewrite/rewrite-migrate-java/commit/6f08933445b7a0db096a478ff65bbd6a1fae5bcc) I have added guards against removing `catch (Exception e)` blocks and against modifying a class when another `Base64` is present.  

Thanks for reporting.
