### ISSUE TITLE
More jaxb related issues - metro - webservices jars

### ISSUE THREAD

**Issue by hazendaz** [openrewrite/rewrite-migrate-java#224]
There are a number of tickets opened and closed on very similar issue.  Its well known that jaxws jaxb and related items are branded all over the place.  I think more needs done to understand that here so that incorrect binaries are not being added.

Example that I currently am running into is with 

webservices-api / webservices-rt

Those are java metro jars.  I shouldn't get jaxb jars additionally added.  Currently the UpgradeToJava17 recipe will add jaxb-runtime.  That runtime is part of webservices-rt with additional glue.  I presume same issue with both JavaEE and JakartaEE.

I did not see webservices mentioned here in the existing ones but rather the even slimmer versions of those type modules jaxws-rt for example.

Overall this is a complicated one, but I think the entire list of items needs to be looked at to understand what it should be doing.  While I know this and know to just discard that change, I fear too many won't and if they try to go modular later or if using mavens buggy javadoc plugin it will get duplicate modules and not compile.

**Comment by MBoegers** [comment]
I observed a similar problem with `org.openrewrite.java.migrate.Java8toJava11`.

We depend on `org.springframework.boot:spint-boot-starter-web-services:2.7.10.` which brings `jakarta.activation:jakarta.activation:1.2.2` transitively.
The Java8toJava11 recipe add `com.sun.xml.ws:jaxwsrt:2.3.6` that shadows javax.axtivation and lead to a compile time error.

@timtebeek and I shortly discussed this (and another) problem [here](https://rewriteoss.slack.com/archives/C01A843MWG5/p1684938331728659?thread_ts=1684838934.811569&cid=C01A843MWG5). 
I also came up with a few ideas but agree with @hazendaz its seems to be a bigger problem than _only_ one recipe acting weird :D

**Comment by timtebeek** [comment]
Yes I appreciate both your concerns, and bringing this to our attention. I fear I might lack some background as to what exactly would have to change, but will gladly work with you all to come to better handling to resolve these issues. From the above I get the sense that we should detect more of the "branded" jaxws jaxb dependencies, and hold off from adding additional jaxb dependencies when those are detected. Did I get that right?

And would you be open to providing a list of such branded GAVs that indicate no additional jaxb dependencies should be added?
My guess is these should then go into [AddJaxbRuntime.java](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/javax/AddJaxbRuntime.java) & [AddJaxwsRuntime.java](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/javax/AddJaxwsRuntime.java), as additional exceptions.
The clearest start to better handling would be additional test cases for [AddJaxbDependenciesTest.java](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/test/java/org/openrewrite/java/migrate/javax/AddJaxbDependenciesTest.java) and [AddJaxwsDependenciesTest.java](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/test/java/org/openrewrite/java/migrate/javax/AddJaxwsDependenciesTest.java), such that we can verify our handling is as we want it to be.

**Comment by timtebeek** [comment]
We've had a recent change in https://github.com/openrewrite/rewrite-migrate-java/commit/b6215379d0de1d63bcd19de5952d5edd3073b21b that limits the applicability of the recipe. I'm optimistic that closes this issue too, but feel free to reopen if you're still seeing issues.
