### ISSUE TITLE
StringUtils.defaultString ->  Objects.toString

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#267]
```java

    package org.apache.commons.lang3; 


    /**
     * Returns either the given String, or if the String is
     * {@code null}, {@code nullDefault}.
     *
     * <pre>
     * StringUtils.defaultString(null, "NULL")  = "NULL"
     * StringUtils.defaultString("", "NULL")    = ""
     * StringUtils.defaultString("bat", "NULL") = "bat"
     * </pre>
     *
     * @see Objects#toString(Object, String)
     * @see String#valueOf(Object)
     * @param str  the String to check, may be null
     * @param nullDefault  the default String to return
     *  if the input is {@code null}, may be null
     * @return the passed in String, or the default if it was {@code null}
     * @deprecated Use {@link Objects#toString(Object, String)}
     */
    @Deprecated
    public static String defaultString(final String str, final String nullDefault) {
        return Objects.toString(str, nullDefault);
    }



```

**Comment by timtebeek** [comment]
I'm guessing you're referring to [the Apache Commons StringUtils class](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#defaultString-java.lang.String-java.lang.String-) here? Since there's quite a few different variant. :)

And would you be open to contributing such a recipe?

**Comment by yeikel** [comment]
> I'm guessing you're referring to [the Apache Commons StringUtils class](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#defaultString-java.lang.String-java.lang.String-) here? Since there's quite a few different variant. :)
> 

I just added the package definition to avoid confusions :) 

> And would you be open to contributing such a recipe?
I can give it a try when I get some capacity but I can't commit to anything concrete right now. 

Thank you!

**Comment by timtebeek** [comment]
Got started on a configurable recipe approach, that might allow us to quickly add a few more; curious to hear your thoughts!
https://github.com/openrewrite/rewrite-migrate-java/pull/268

**Comment by timtebeek** [comment]
So this took a little longer, but we now have good support for a much simpler way to define recipes; feel free to go over https://github.com/openrewrite/rewrite-migrate-java/pull/271
