### ISSUE TITLE
Incompatible use of <release> parameter in the configuration of maven-compiler-plugin

### ISSUE THREAD

**Issue by nguyenhoan** [openrewrite/rewrite-migrate-java#279]
## What version of OpenRewrite are you using?
I am using

- Maven 3.9.3
- rewrite-migrate-java:RELEASE

## How are you running OpenRewrite?
I am using Maven command line
```
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:RELEASE \
  -Drewrite.activeRecipes=org.openrewrite.java.migrate.UpgradeToJava17
```
as instructed in [usage](https://docs.openrewrite.org/recipes/java/migrate/upgradetojava17#usage)

I ran OpenRewrite on this public GitHub project
https://github.com/codesofun/web-bee
at the tip commit, 11cfb6f2194874fb6d65b851f8a26968376b21da, at the time of the experiment.

## What is the smallest, simplest way to reproduce the problem?
- Git clone the above project
- Run the above Maven command

## What did you expect to see?
```
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

## What did you see instead?
```
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <release>17</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
OpenRewrite seems to have a bug when using the parameter `<release>` to specify the language version for the compiler in place of `<source>` and `<target>`. However, this parameter [`<release>`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release) is introduced in 3.6 and this project uses an older version of `maven-compiler-plugin` in which case Maven will ignore that `<release>`, and consider [`<source>`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#source) and [`<target>`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#target) as undefined and use their default values of 1.5. This led to compile error as source and target option of 5 are no longer supported by Maven compiler plugin.

## What is the full stack trace of any errors you encountered?
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project webBee-core: Compilation failure: Compilation failure: 
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I am happy to work with someone from your team on this.

**Comment by knutwannheden** [comment]
@nguyenhoan Thanks for the report! Since the Maven Compiler Plugin 3.6.0 was released way back in 2016, I think it would make sense if we instead were to also upgrade the plugin to at least version 3.6.2 (from 2017). But honestly, I don't know if this could introduce any incompatibilities.

**Comment by knutwannheden** [comment]
I suggest we add a recipe as follows to `java-version-11.yml` just before the `UseMavenCompilerPluginReleaseConfiguration` recipe:
```yml
  - org.openrewrite.maven.UpgradePluginVersion:
      groupId: org.apache.maven.plugins
      artifactId: maven-compiler-plugin
      newVersion: 3.6.2
```
Then amend the existing unit test https://github.com/openrewrite/rewrite-migrate-java/blob/e0e5b9d6afc53f51f6f61ac7517da9506e17687d/src/test/java/org/openrewrite/java/migrate/UpgradeToJava17Test.java#L41 to verify that it works.

@nguyenhoan Are you interested in providing a PR for this?

**Comment by nguyenhoan** [comment]
Thanks for the instructions!
Here is the PR
https://github.com/openrewrite/rewrite-migrate-java/pull/281

**Comment by knutwannheden** [comment]
Depending on how your settings.xml you can use the `LATEST` pseudo version already now instead `RELEASE` when refering to the recipe artifact, since a snapshot build should already have been published. The next release will probably come out within the next few weeks.

**Comment by nguyenhoan** [comment]
Awesome! Thank you!
