### ISSUE TITLE
Feature request: recipe for migrating to Java 21

### ISSUE THREAD

**Issue by matsev** [openrewrite/rewrite-migrate-java#305]
## What problem are you trying to solve?
Recipe for automated migration to Java 21 

## Describe the solution you'd like
A recipe that automates Java migration from version 17 to 21, c.f. existing [Java migration recipies](https://github.com/openrewrite/rewrite-migrate-java#java-migration-recipes)

## Have you considered any alternatives or workarounds?
No

## Additional context
- #243
- #297 
- #306 

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?
Not at the moment

**Comment by timtebeek** [comment]
hi @matsev ; thanks for logging this request here! As you saw we already had two PRs related to Java 21
 - https://github.com/openrewrite/rewrite-migrate-java/pull/297
 - https://github.com/openrewrite/rewrite-migrate-java/issues/243

We're right now waiting for this issue & Gradle 8.4 before we're (easily) actually able to continue work on Java 21:
- https://github.com/gradle/gradle/issues/25574
- https://docs.gradle.org/8.4-rc-1/release-notes.html

Are there any particular migration recipes for Java 21 that you're looking forward to? It might make sense to log those as separate issues with links to the JEPs / release notes, as that makes it easier pick those up and close an issue.

We'd also need to add a Java 21 specific parser, similar to [the Java 8, 11 and 17 parsers in OpenRewrite/rewrite](https://github.com/openrewrite/rewrite). That way you're not stuck on Java 21 without OpenRewrite support. Also best tracked as a separate issue I suppose.

**Comment by matsev** [comment]
Thanks for your comment. Sequenced collection was the first thing that crossed my mind, but after looking at the [Java 21 release notes](https://jdk.java.net/21/release-notes) I decided to create another ticket for [JEP 441: Pattern Matching for switch](https://openjdk.org/jeps/441) (and possibly also for the related [JEP 440: Record Patterns](https://openjdk.org/jeps/440)), please see #306

**Comment by timtebeek** [comment]
Thanks a lot! Helps to have them targeted to a particular use case, and thanks for the detail in reporting
- #306

**Comment by timtebeek** [comment]
Now using gradle 8.4 here and in rewrite core, for Java 21 support; one step closer.

**Comment by timtebeek** [comment]
We now have a decent first set of recipes to migrate to Java 21:
https://docs.openrewrite.org/recipes/java/migrate/upgradetojava21

Closing this issue in favor of individual issues for further migration recipes.
