### ISSUE TITLE
Migrate from Apache HttpClient 4.x to Apache HttpClient 5.x

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-migrate-java#311]
## What problem are you trying to solve?

Migrate from Apache HttpClient 4.x to Apache HttpClient 5.x.

## Describe the solution you'd like

We need to migrated from Apache HttpClient 4.x to Apache HttpClient 5.x. and the steps are listed [here](https://hc.apache.org/httpcomponents-client-5.2.x/migration-guide/index.html) and [here](https://hc.apache.org/httpcomponents-client-5.2.x/migration-guide/migration-to-classic.html).

## Additional context

This was a fall-out from the Spring Boot migration as Spring Boot now uses Apache HttpClient 5.x internally.

**Comment by timtebeek** [comment]
Hi @rdifrango ; did you happen to spot [the Apache HttpClient 4 to 5 migration](https://docs.openrewrite.org/recipes/java/apache/httpclient5/upgradeapachehttpclient_5) recipes [in rewrite-spring](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/resources/META-INF/rewrite/apache-httpclient-4-5.yml)?
We've moved them there as indeed it's a common migration steps for folks upgrading Spring Boot.

Hope that helps you migrate! If you find any issues please report those against rewrite-spring; we'd love to get more feedback & coverage on those recipes.

**Comment by timtebeek** [comment]
But you are able to proceed with those recipes for now right? Just making sure you're not blocked. :)

**Comment by rdifrango** [comment]
> But you are able to proceed with those recipes for now right? Just making sure you're not blocked. :)

I am, we just ended up making the changes manually, but I may try and go back and re-run on the previous code based to see if the changes match-up.
