### ISSUE TITLE
Guava `Joiner.on(delimiter).join(list)` to `String.join(delimiter, list)`

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-migrate-java#318]
This will contribute to https://docs.openrewrite.org/recipes/java/migrate/guava/noguava (because this method is available since (at least) Java 8: https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.Iterable-)

Full API: https://guava.dev/releases/16.0/api/docs/com/google/common/base/Joiner.html

In case a class contains `Joiner.on(delimiter).join(list)` only, this could be removed. - Happend in our project. Maybe an edge case, because Joiner can do much more.

This refs https://github.com/openrewrite/rewrite-migrate-java/issues/101

**Comment by timtebeek** [comment]
Fixed in https://github.com/openrewrite/rewrite-migrate-java/pull/389 by @tobli 🎉
