### ISSUE TITLE
Upgrade maven-compiler-plugin version + handle source/target configuration

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-migrate-java#37]
Can log handling the configuration of `source/target` to `release` as a separate issue from bumping the plugin version itself.

This may be tricky because there are variations on this; e.g., some folks having their `<configuration>` keyed with `<source>` + `<target>`, some using `<release>`, people using Spring Boot can use `<java.version>`, etc.

Generally, though, something to the effect of:

```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.6.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
```

going to

```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
            <release>11</release>
        </configuration>
      </plugin>
```

---

Possibly a problem for upstream rewrite-- plugins under the groupId `org.apache.maven.plugins` do not always have their groupId explicitly declared in a user's `pom.xml`; declaring them are optional. They are considered part of the default pom. It appears doing `UpgradePluginVersion` (or any other plugin-related recipe) on a groupId/artifactId such as `org.apache.maven.plugins/maven-compiler-plugin` only works if a user has the groupId explicitly declared. Can log this separately.

Pasting for convenience:
```yml
  - org.openrewrite.maven.UpgradePluginVersion:
      groupId: org.apache.maven.plugins
      artifactId: maven-compiler-plugin
      newVersion: 3.8.x
```

**Comment by timtebeek** [comment]
Fixed in #149 , with the separate issue picked up in https://github.com/openrewrite/rewrite/issues/3529
