### ISSUE TITLE
`JavaxBeansXmlToJakartaBeansXml` also updates namespace in Spring application context xml

### ISSUE THREAD

**Issue by jpraet** [openrewrite/rewrite-migrate-java#385]
## What version of OpenRewrite are you using?

- Maven plugin v5.17.1

## What is the smallest, simplest way to reproduce the problem?

test.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

    <!-- bean definitions here -->

</beans>
```

## What did you expect to see?

test.xml Spring application context remains unchanged.

## What did you see instead?

Namespace is updated.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="https://jakarta.ee/xml/ns/jakartaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/beans_3_0.xsd">

    <!-- bean definitions here -->

</beans>
```

**Comment by timtebeek** [comment]
Hi @jpraet ; thanks for reporting this here! Seems like an oversight indeed, which I hope to fix in:
- https://github.com/openrewrite/rewrite-migrate-java/pull/386

**Comment by melloware** [comment]
sorry about that @jpraet i totally forgot Spring Beans had a similar namespace!  Great fix @timtebeek
