### ISSUE TITLE
Support ByteStreams.toByteArray -> inputStream.readAllBytes()

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-migrate-java#390]
Instead of Guava's [ByteStreams#toByteArray()](https://guava.dev/releases/19.0/api/docs/com/google/common/io/ByteStreams.html#toByteArray(java.io.InputStream)), [InputStream.html#readAllBytes](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/io/InputStream.html#readAllBytes--) should be used. The latter is available since Java 9.

```diff
- String inputStr = new String(ByteStreams. toByteArray(inputStream), Charsets.UJTF_8);
+ String inputStr = new String(inputStream.readAllBytes()), Charsets.UJTF_8);
```

Should IMHO be doable with [Refaster templates](https://docs.openrewrite.org/authoring-recipes/types-of-recipes#refaster-templates)?

**Comment by timtebeek** [comment]
Indeed looks like a good candidate! I've moved the issue to rewrite-migrate-java since that's where we already have our other Guava recipes and the rewrite-templating dependency. I'm doubting if the recipe would even need the `new String(... )` surrounding it. (anyone) welcome to give this a go! :)

**Comment by Stephan202** [comment]
> I'm doubting if the recipe would even need the `new String(... ) ` surrounding it.

Indeed, better to omit that and make the rule more generally applicable. :+1: I filed PicnicSupermarket/error-prone-support#963, but feel free to copy over to this repo. Sharing is caring ;)

**Comment by Siedlerchr** [comment]
Just be careful, this does not work under Android 9 & 10. I recently had the issue...

**Comment by timtebeek** [comment]
> > I'm doubting if the recipe would even need the `new String(... ) ` surrounding it.
> 
> Indeed, better to omit that and make the rule more generally applicable. 👍 I filed [PicnicSupermarket/error-prone-support#963](https://github.com/PicnicSupermarket/error-prone-support/pull/963), but feel free to copy over to this repo. Sharing is caring ;)

Probably good to have our own copy here as well, to fit in with our no guava recipes. Thanks for the reference implementation @Stephan202 ! Would you want to add that here @koppor ? Then we can also run it at scale here.

Longer term we could look at adding [Picnicsupermarket/error-prone-support](https://github.com/Picnicsupermarket/error-prone-support/) as a dependency here and reference recipes from there in our composite yaml recipes, but that first needs a new release of EPS and some work on correctly attributing those recipes to the authors there. :)

**Comment by Stephan202** [comment]
> but that first needs a new release of EPS

@rickie and I have started to talk about doing a new release. Could be a few weeks (lots of other stuff going on), but hopefully less!

**Comment by timtebeek** [comment]
Turns out we have an interesting challenge when we want to integrate this into rewrite-migrate-java, which still uses Java 8.
![image](https://github.com/openrewrite/rewrite-migrate-java/assets/1027334/d1d16605-0722-410e-a11f-f36a0a7613ae)

We might need to add a second source set of Refaster recipe classes does no make it into the the final jar, but do contribute the generated Java 8 runtime compatible recipes. 🤔 Fun corner case this. /cc @knutwannheden

**Comment by knutwannheden** [comment]
Yes, this issue has also crossed my mind. And indeed I think we should be able to add a separate source set. Another question would be if this should somehow automatically add a precondition for the required Java version. We should be able to check that somehow. But that would be more of a nice-to-have, I think.

**Comment by timtebeek** [comment]
Neat; figured get start with that in https://github.com/openrewrite/rewrite-migrate-java/pull/399; Although come to think of it that might require us to complete https://github.com/openrewrite/rewrite-templating/pull/57 first
- https://github.com/openrewrite/rewrite-templating/pull/57

**Comment by timtebeek** [comment]
This has since made it into our recipe catalog via ErrorProne Support:
- https://docs.openrewrite.org/recipes/tech/picnic/errorprone/refasterrules/inputstreamrulesrecipes$inputstreamreadallbytesrecipe
- https://github.com/PicnicSupermarket/error-prone-support/pull/963
- https://github.com/PicnicSupermarket/error-prone-support/pull/1270

Thanks again for the suggestion!
