### ISSUE TITLE
Java 21+ : Remove Extra Semicolons Between "import" Statements

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#396]
## What problem are you trying to solve?

> The Java Language Specification does not allow extra semicolons to appear between `import` statements, yet the compiler was allowing them; [[JDK-8027682](https://bugs.openjdk.org/browse/JDK-8027682)](https://bugs.openjdk.org/browse/JDK-8027682) fixed this.

As a result, a program like this, which previously would have compiled successfully:

```java
    import java.util.Map;;;;
    import java.util.Set;
    class Test { }

```
will now generate an error:

```java
    Test.java:1: error: extraneous semicolon
    import java.util.Map;;;;
                         ^
```
## What precondition(s) should be checked before applying this recipe?

We should be able to apply this recipe in any Java version but it is important to apply it during the Java 21 migration

## Describe the situation before applying the recipe

```java
import org.mockito.Mock;;
```

## Describe the situation after applying the recipe
```diff
-import org.mockito.Mock;;
+import org.mockito.Mock;
```

## Any additional context

https://bugs.openjdk.org/browse/JDK-8027682

**Comment by timtebeek** [comment]
I wow, I had no idea; Interesting case though and presumably relatively straightforward to write a recipe for. Thanks for the suggestion!

**Comment by timtebeek** [comment]
Fixed in 
- https://github.com/openrewrite/rewrite-migrate-java/pull/404
