### ISSUE TITLE
`UseTextBlocks` should not delete comments

### ISSUE THREAD

**Issue by aholland** [openrewrite/rewrite-migrate-java#397]
<img width="1851" alt="image" src="https://github.com/openrewrite/rewrite-gradle-plugin/assets/1101312/5dd6a439-9c3f-4f5c-9d6e-53f649b9a47e">

Hi - there are two problems with the way text blocks are being created, illustrated in this image.
1. The comments in the original have been deleted. There is no good way to insert comments into a text block, but in such cases you could just leave the old syntax in place.
2. When you're creating text block within an annotation like this, there is no need for the trailing `\` . I admit this might be hard to detect and do correctly and reliably. Perhaps there could be an option though.

This bug report is really about 1.

I am using the Gradle plugin, version 6.6.4.

**Comment by timtebeek** [comment]
Your second comment of ending up with trailing slashes in SQL queries is maybe best handled with a run of our Format SQL recipe: https://docs.openrewrite.org/recipes/sql/formatsql. I think that ought to already introduce newlines, [as seen in the tests](https://github.com/openrewrite/rewrite-sql/blob/2b5b939112cb34a02d8a738e69d9f7248676d014/src/test/java/org/openrewrite/sql/FormatSqlTest.java#L70-L87).

**Comment by BramliAK** [comment]
Hello @timtebeek i think that this issue was already fixed, i maked some test and we are not converting to text blocks when there's comments.

**Comment by timtebeek** [comment]
Awesome, thanks a lot for confirming!
