### ISSUE TITLE
Question: jdeprscan vs -Werror

### ISSUE THREAD

**Issue by binkley** [openrewrite/rewrite-migrate-java#4]
This is a question, not an issue.  Perhaps it is an issue for update to `README.md`?

How does using jdeprscan differ from adding `-Werror` and `-Xlint:deprecation` to my build?

**Comment by tkvangorder** [comment]
Good question:

`jdeprscan` is specifically targeting deprecations within the standard java libraries whereas `-Werror -Xlint:deprecation` would fail on any usage of a deprecated API, be it from the standard libraries, any third-party libraries, or your own source code. You can also target `jdeprscan` to a specific version of Java and it will only report deprecations relevant for that release.

To get an idea of the issues it will report for Java 11:

`jdeprscan --release 11 --list`
