### ISSUE TITLE
Replace "JDK internals" in recipes description with "JDK provided API"

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite-migrate-java#411]
## What problem are you trying to solve?
[Some recipes](https://github.com/search?q=repo%3Aopenrewrite%2Frewrite-migrate-java%20JDK%20internals&type=code) use the wording "Replace xxx with JDK internals".

JDK internals is ambiguous, we can think that we're talking about JDK internal API that are not guaranteed for long term stability.

## Describe the solution you'd like
Replace "JDK internals" in recipes description with "JDK provided API"

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?
Yes

**Comment by timtebeek** [comment]
Thanks for pointing that out & offering to help! Indeed like your proposal better.
