### ISSUE TITLE
Replace Guava Maps.newHashMap()

### ISSUE THREAD

**Issue by timo-abele** [openrewrite/rewrite-migrate-java#412]
## What problem are you trying to solve?

Per https://guava.dev/releases/23.6-jre/api/docs/com/google/common/collect/Maps.html#newHashMap--
`new HashMap()` from the standard lib shoud be preferred to guava's `Maps.newHashMap()`

There are many similar recipes already, e.g. https://docs.openrewrite.org/recipes/java/migrate/guava/noguavasetsnewconcurrenthashset, but this one has apparently slipped through.

## Describe the situation before applying the recipe

```java
import com.google.common.collect.Maps;
class A {
    void foo(String bar) {
        Map<Integer, String> numbers = Maps.newHashMap();
    }
}
```

## Describe the situation after applying the recipe

```java
import java.util.HashMap;
class A {
    void foo(String bar) {
        Map<Integer, String> numbers = new HashMap<>()
  }
}
```

**Comment by timtebeek** [comment]
Surprised we didn't have this one already indeed! Should be easy enough to add. Would you want to help out there?
