### ISSUE TITLE
Migrate to `jakarta.validation` does not update META-INF/services/javax.validation.ConstraintValidator

### ISSUE THREAD

**Issue by arnaldop** [openrewrite/rewrite-migrate-java#478]
The recipe https://docs.openrewrite.org/recipes/java/migrate/jakarta/javaxvalidationmigrationtojakartavalidation does not update the file `META-INF/services/javax.validation.ConstraintValidator`. This causes validations to fail because the validator class (which is defined in the file) is not registered.

`META-INF/services/javax.validation.ConstraintValidator` -> `META-INF/services/jakarta.validation.ConstraintValidator`

**Comment by melloware** [comment]
I can look at this one

**Comment by timtebeek** [comment]
Thanks for the report @arnaldop and thanks for the offer to help @melloware ! If it's just the file rename, then a quick three lines of yaml added in `src/main/resource/META-INF/rewrite` to the appropriate recipe could be enough: https://docs.openrewrite.org/recipes/core/renamefile

**Comment by melloware** [comment]
Yep and I think we also need to update javax. to jakarta. inside `ValidationMessage.properties` see: https://github.com/hibernate/hibernate-validator/blob/main/engine/src/main/resources/org/hibernate/validator/ValidationMessages.properties

**Comment by melloware** [comment]
@timtebeek i think we might need a sparate ticket to do Beans 3.0 `META-INF/validation.xml` for EE10 just like I did ejb-jar.xml recently.

see: https://jakarta.ee/specifications/bean-validation/3.0/jakarta-bean-validation-spec-3.0.html#validationapi-bootstrapping-xmlconfiguration
