### ISSUE TITLE
Rewrite of empty `Set.of()` by UseEnumSetOf doesn't compile

### ISSUE THREAD

**Issue by olayinkasf** [openrewrite/rewrite-migrate-java#490]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.27.1
- Maven plugin v5.32.1
- rewrite-_module_ v2.16.0

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>5.32.1</version>
  <configuration>
    ... 
  </configuration>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
class A {
    void foo(String bar) {
        final Set<TimeUnit> timeUnits = Set.of();
    }
}
```

## What did you expect to see?

Either use `EnumSet.noneOf` or do not do any rewrite
```java
class A {
    void foo(String bar) {
        final Set<TimeUnit> timeUnits = EnumSet.noneOf(TimeUnit.class);
    }
}
```

## What did you see instead?

Uses `EnumSet.of` which requires an argument and since there is none, the code below does not compile
```java
class A {
    void foo(String bar) {
        final Set<TimeUnit> timeUnits = EnumSet.of();
    }
}
```

## What is the full stack trace of any errors you encountered?

No exception from plugin. Rewritten code isn't compilable.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I can fix it when I have time but I don't know when I will so please feel free to do that.

**Comment by timtebeek** [comment]
Oh wow, thanks for reporting the issues you're finding! Seems like a straightforward special case replacement to get this fixed.
