### ISSUE TITLE
UseTextBlocks incorrectly converts multi-line concatenated string to text block in Kotlin

### ISSUE THREAD

**Issue by eocantu** [openrewrite/rewrite-migrate-java#501]
## What version of OpenRewrite are you using?

I am using

- rewrite-maven-plugin v5.34.1
- rewrite-java v8.28.1
- rewrite-spring v5.13.2

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a multi-module project: https://github.com/eocantu/spring-boot-demo

## What is the smallest, simplest way to reproduce the problem?

```kotlin
const val MULTI_LINE_MESSAGE =
    "This is a multi-line message to show what happens. " +
            "This is the second line of such message."

```

## What did you expect to see?

No change

## What did you see instead?

```kotlin
 const val MULTI_LINE_MESSAGE =
    """
    This is a multi-line message to show what happens. \
    This is the second line of such message.\
    """
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Maybe

**Comment by eocantu** [comment]
Thanks for the quick reply, @timtebeek!

The problem I see is that the string is no longer the same. In this example, it was originally:
```
This is a multi-line message to show what happens. This is the second line of such message.
```

And became the following (leading spaces, backslash character, new lines):
```

    This is a multi-line message to show what happens. \
    This is the second line of such message.\
        
```

In Java, the indentation is trimmed automatically in a text block. That's not the case in Kotlin, you'd need to trim explicitly. And even then, there are places where using something like `.trimIndent()` isn't possible (e.g. constants).


> If we want to completely exclude running this recipe for Kotlin, then we could do something similar as to what we do [here](https://github.com/openrewrite/rewrite-static-analysis/blob/32afee0f2b4901229b8980c940396211d52be9ec/src/main/java/org/openrewrite/staticanalysis/StringLiteralEquality.java#L59-L65) for StringLiteralEquality.

I think that would be better than ending up with a different string.

**Comment by timtebeek** [comment]
Thanks for the quick and detailed feedback; I forgot about the trimIdent momentarily. Best then to skip it indeed. Would that be something you're open to add & can you fit that in? Not expected of course, but certainly appreciated if it were possible.

**Comment by eocantu** [comment]
It seems pretty straight forward based on the example you linked. I can give it a try.
