### ISSUE TITLE
UseEnumSetOf rewrite breaks for varargs parameter

### ISSUE THREAD

**Issue by mbruggmann** [openrewrite/rewrite-migrate-java#516]
## What version of OpenRewrite are you using?
rewrite-migrate-java 2.20.0

## What is the smallest, simplest way to reproduce the problem?
I can reproduce the issue with the following testcase:
```java

  @Test
  void enumSetOfVarargs() {
    rewriteRun(
        spec -> spec.recipe(new UseEnumSetOf()),
        java(
            """
            package com.helloworld;

            import java.util.concurrent.TimeUnit;
            import java.util.Set;

            public class Main {

              public Set<TimeUnit> method(final TimeUnit... units) {
                final Set<TimeUnit> asSet = Set.of(units);
                return asSet;
              }

            }"""));
  }
}

```

## What did you expect to see?
Either to bail out and keep it as is. 

Or alternatively we could translate the varargs parameter into a collection first, e.g.
```java
public Set<TimeUnit> method(final TimeUnit... units) {
  final Set<TimeUnit> asSet = EnumSet.noneOf(TimeUnit.class);
  asSet.addAll(Arrays.asList(units));
  return asSet;
}
```
Note that the more convenient-looking `EnumSet.copyOf(asList(units))` throws an exception for empty array.

## What did you see instead?
```java
public Set<TimeUnit> method(final TimeUnit... units) {
  final Set<TimeUnit> asSet = EnumSet.of(units);
  return asSet;
}
```
(doesn't compile)

**Comment by timtebeek** [comment]
Thanks for the report @mbruggmann ! Bail and return the original LST element is likely the quickest safe fix when there's a potentially empty array as argument. Is this something you'd be open to take on?

**Comment by mbruggmann** [comment]
@timtebeek Seemed simple enough so I gave it a go: #518
