### ISSUE TITLE
Convert javax to jakarta to imperative recipes

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-migrate-java#52]
Found in BroadLeafCommerce.

Problem:
The `javax` to `jakarta` recipe, does not add `jakarta 3.x` dependencies and changes the applicable packages from `javax` to `jakarta`.

`jakarta 2.3.x` dependencies that use the `javax` namespace may exist in the project transitively.
AddDependency detects the artifact and does not add explicit dependencies, so the UpgradeDepdency to `3.x` fails.

**Comment by pway99** [comment]
This issue has been resolved.
