### ISSUE TITLE
`maven.compiler.release` set in parent is not recognized in child module

### ISSUE THREAD

**Issue by pzygielo** [openrewrite/rewrite-migrate-java#523]
`maven.compiler.release` which is defined in parent is not recognized in child module and patch for explicit overriding property is generated by `UpgradeToJava17` recipe.

## What version of OpenRewrite are you using?
I am using
- rewrite-migrate-java 2.21.0
- Maven plugin 5.37.1

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a multi-module project.

## What is the smallest, simplest way to reproduce the problem?
https://github.com/pzrep/openrewrite-migrate-compiler-release-in-child/

## What did you expect to see?
No patch generated by recipe as property inherited from parent is good enough.

## What did you see instead?
Patch generated by recipe (step: Show applied changes): https://github.com/pzrep/openrewrite-migrate-compiler-release-in-child/actions/runs/10196871940/job/28208511361?pr=2

```diff
diff --git a/child/pom.xml b/child/pom.xml
index 96186f3..2570020 100644
--- a/child/pom.xml
+++ b/child/pom.xml
@@ -8,5 +8,8 @@
         <version>1-SNAPSHOT</version>
     </parent>
     <artifactId>openrewrite-migrate-compiler-release-in-child.child</artifactId>
+    <properties>
+        <maven.compiler.release>17</maven.compiler.release>
+    </properties>
```

https://github.com/openrewrite/rewrite-migrate-java/commit/8d15935263b802d709861c0509c17dfbfae8109b#commitcomment-144892557

**Comment by pzygielo** [comment]
Additional info: I observe, that `m.c.r` property is added even to `pom.xml` in aggregator project (of `<packaging>pom</packaging>`), where no compilation happens.

**Comment by timtebeek** [comment]
Thanks for the reproducer @pzygielo ! Next steps would be to turn this into a runnable unit test and see that it's resolved.

For the aggregator poms I'm not sure how you'd handle those separately, as we would like to set the property in parent poms, not each submodule. How would you recognize those cases?

/cc @sambsnyd for visibility

**Comment by pzygielo** [comment]
> For the aggregator poms I'm not sure how you'd handle those separately, as we would like to set the property in parent poms, not each submodule. 

That's what I'd like to see as well. My reference to modified aggregator in comment above was probably unnecessary, as in my case this aggregator is also a parent (which does not need to be the case in general - but I can't tell about plain aggregator yet).

**Comment by DidierLoiseau** [comment]
I must say this is quite annoying because it adds it everywhere when your microservices & libraries inherit the `spring-boot-starter-parent` pom and don’t redeclare it.

I haven’t checked, but wouldn’t it also override a higher java version specified in a parent?

Would you think it is some kind of regression or has it always been like this?

**Comment by pzygielo** [comment]
> Would you think it is some kind of regression or has it always been like this?

I have not seen this in 2.20.0.

**Comment by DidierLoiseau** [comment]
I confirm it was introduced in 2.21.0 – maybe a regression from commit 8d15935263b802d709861c0509c17dfbfae8109b?

I also confirm it downgrades java if a higher version is specified in the parent pom.
