### ISSUE TITLE
org.openrewrite.java.migrate.lombok.LombokValToFinalVar does not clean up imports

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite-migrate-java#539]
## What is the smallest, simplest way to reproduce the problem?

```java
import lombok.val;

class A {
    void foo(String bar) {
        final val expected = 123456789L;
    }
}
```

## What did you expect to see?

```java
class A {
    void foo(String bar) {
        final var expected = 123456789L;
    }
}
```

## What did you see instead?

```java
import lombok.val;

class A {
    void foo(String bar) {
        final var expected = 123456789L;
    }
}
```

https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/lombok/LombokValToFinalVar.java doesn't clean up the removal?

**Comment by timtebeek** [comment]
Thanks for the report! Should be fixed now after https://github.com/openrewrite/rewrite-migrate-java/commit/3d8fbd0e8fc7c121cd978d569ed6e1435f9328e5
