### ISSUE TITLE
UseTextBlocks creating unnecessary trailing escape

### ISSUE THREAD

**Issue by protocol7** [openrewrite/rewrite-migrate-java#555]
## What version of OpenRewrite are you using?

- org.openrewrite:rewrite-core:8.35.0
- org.openrewrite.recipe:rewrite-migrate-java:2.24.0

## What is the smallest, simplest way to reproduce the problem?

```java
  @Test
  void textBlockTrailingEscape() {
    assertEquals(
        """
        hello\
        """,
        """
        hello""");

    rewriteRun(
        spec -> spec.recipe(new UseTextBlocks()),
        java(
            """
             package com.helloworld;

             public class Main {
                 String foo =
                     "hello\\n"
                         + "world";
            }""",
            """
             package com.helloworld;

             public class Main {
                 String foo =
                     \"""
                     hello
                     world\""";
            }""",
            src -> src.markers(javaVersion(17))));
  }
```

## What did you expect to see?

The escape after `world` is not needed are merely adds noise. Instead, the text block could be:

```
"""
hello
world"""
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Likely not in the near-term due to other commitments.

**Comment by timtebeek** [comment]
Thanks for the clear example!
