### ISSUE TITLE
Question about `UseTextBlocks`

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-migrate-java#589]
## How are you running OpenRewrite?

The issue is present in the tests.

## What is the smallest, simplest way to reproduce the problem?
https://github.com/openrewrite/rewrite-migrate-java/blob/460fad7fec51d39bf5e3c02e0fb270946361e95e/src/test/java/org/openrewrite/java/migrate/lang/UseTextBlocksTest.java#L273-L297

## What did you expect to see?
```java
              class Test {
                  String query = \"""
                          SELECT * FROM
                          my_table
                          WHERE something = 1;
                          \""";
              }
```

## What did you see instead?
Test result:
```java
              class Test {
                  String query = \"""
                          SELECT * FROM
                          my_table
                          WHERE something = 1;\""";
              }
```

## What is the full stack trace of any errors you encountered?
N/A.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
I don't know, this is mostly a question.

Currently, the recipe leaves unnecessary escapes in the code. It sucks to manually clean up the results and seems unnecessary. The tests assert that it's expected behavior and I'm curious why the characters are left in the recipe's result.

It's not a big deal for hundreds of tests, but the results become impactful across thousands. Does anyone know why the escapes are left in the code?

**Comment by timtebeek** [comment]
Hi @traceyyoshima ; the underlying Strings in the expected and actual are different though, right? The current "after" value ends on a `;` as the original input String, whereas the proposal of what you expected to see ends in a newline, unless that's escaped.

So the escape that you're seeing is there to preserve the original String value. Alternatively I think we could have placed the closing `"""` on the same line, but then that can look odd in it's own way as well. This way we are consistent with the placement of our closing `"""`, and through that the left hand trimming that Java does based on it's placement.

I agree it might take some getting used to, but to me at least there isn't directly an alternative that I like better than what we have. What are your thoughts based on the above?

**Comment by traceyyoshima** [comment]
> Hi @traceyyoshima ; the underlying Strings in the expected and actual are different though, right? The current "after" value ends on a `;` as the original input String, whereas the proposal of what you expected to see ends in a newline, unless that's escaped.
> 
> So the escape that you're seeing is there to preserve the original String value. Alternatively I think we could have placed the closing `"""` on the same line, but then that can look odd in it's own way as well. This way we are consistent with the placement of our closing `"""`, and through that the left hand trimming that Java does based on it's placement.
> 
> I agree it might take some getting used to, but to me at least there isn't directly an alternative that I like better than what we have. What are your thoughts based on the above?

Ah, my apologies. I updated the example in `What did you see instead?` to clarify. I expected the string to end at the same position without extra code like an `\`. Then, optionally, I could apply formatting if desired. I understand your reasoning, though -- thank you for the clarification.

It's not a big deal since I can use a recipe to make the updates. I was surprised by the outcome. Thanks again

**Comment by timtebeek** [comment]
All good, already figured none of this was new to you, but wanted to be sure just in case, and it might help others reading this as well without the assumed shared knowledge. Glad that your have a way forward from there!

**Comment by knutwannheden** [comment]
I do believe that we should make this recipe a bit more configurable by for example allowing to specify a minimum number of lines it by requiring the string literals to contain `\n` line terminators.
