### ISSUE TITLE
Recipe to Migrate Deprecated Security APIs

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#6]
- [ ] Add a recipe recipe for type/change package for the following classes in `javax.security.cert` #30 
- [ ] javax.net.ssl.HandshakeCompletedEvent.getPeerCertificateChain() -> [getPeerCertificates()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/HandshakeCompletedEvent.html#getPeerCertificates())
- [ ] javax.net.ssl.SSLSession.getPeerCertificateChain() -> [getPeerCertificates()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLSession.html#getPeerCertificates())
- [ ] java.security.AuthProvider(java.lang.String,double,java.lang.String) -> [AuthProvider(String, String, String)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/AuthProvider.html#%3Cinit%3E(java.lang.String,java.lang.String,java.lang.String))
- [ ] class java.security.IdentityScope
- [ ] java.security.Provider(java.lang.String,double,java.lang.String)
- [ ] [double java.security.Provider.getVersion()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/Provider.html#getVersion()) -> [getVersionStr()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/Provider.html#getVersionStr())
- [ ] [java.lang.String java.security.Security.getAlgorithmProperty(java.lang.String,java.lang.String)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/Security.html#getAlgorithmProperty(java.lang.String,java.lang.String)) -> ` AlgorithmParameters and KeyFactory engine classes`
- [ ] [ava.lang.Object java.security.Signature.getParameter(java.lang.String)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/Signature.html#getParameter(java.lang.String))
- [ ] [void java.security.SignatureSpi.engineSetParameter(java.lang.String,java.lang.Object)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/Signature.html#setParameter(java.lang.String,java.lang.Object)) -> [setParameter(AlgorithimParameterSpec)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/Signature.html#setParameter(java.security.spec.AlgorithmParameterSpec))
- [ ] java.lang.Object java.security.SignatureSpi.engineGetParameter(java.lang.String)
- [ ] class java.security.Signer
- [ ] int org.ietf.jgss.GSSContext.initSecContext(java.io.InputStream,java.io.OutputStream)
- [ ] void org.ietf.jgss.GSSContext.acceptSecContext(java.io.InputStream,java.io.OutputStream)
- [ ] void org.ietf.jgss.GSSContext.wrap(java.io.InputStream,java.io.OutputStream,org.ietf.jgss.MessageProp)
- [ ] void org.ietf.jgss.GSSContext.unwrap(java.io.InputStream,java.io.OutputStream,org.ietf.jgss.MessageProp)
- [ ] void org.ietf.jgss.GSSContext.getMIC(java.io.InputStream,java.io.OutputStream,org.ietf.jgss.MessageProp)
- [ ] void org.ietf.jgss.GSSContext.verifyMIC(java.io.InputStream,java.io.InputStream,org.ietf.jgss.MessageProp)
- [ ] interface java.security.Certificate
- [ ] class java.security.Identity

Not sure if there is much of an automated path for the ACL API. (These were removed in Java 14)

```
interface java.security.acl.Acl
interface java.security.acl.AclEntry
class java.security.acl.AclNotFoundException
interface java.security.acl.Group
class java.security.acl.LastOwnerException
class java.security.acl.NotOwnerException
interface java.security.acl.Owner
interface java.security.acl.Permission
```

**Comment by pway99** [comment]
Closing this issue, we can revisit these deprecations if there is a high demand for this at a later date.
