### ISSUE TITLE
Including StringFormatted as part of UpgradeToJava17 seems too opinionated

### ISSUE THREAD

**Issue by jpraet** [openrewrite/rewrite-migrate-java#616]
Should [StringFormatted](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/lang/StringFormatted.java) really be part of [org.openrewrite.java.migrate.UpgradeToJava17](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/resources/META-INF/rewrite/java-version-17.yml)?

It feels a bit too opinionated to me. [String.format()](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/String.html#format(java.lang.String,java.lang.Object...)) isn't deprecated, and replacing it by "".formatted() doesn't always lead to more readable code.

Given that it's [basically impossible to exclude a single recipe](https://github.com/openrewrite/rewrite-maven-plugin/pull/569#issuecomment-1576793092), maybe it could be removed from UpgradeToJava17?

**Comment by timtebeek** [comment]
Hi @jpraet ; I wouldn't say it's impossible; quite the opposite: we've made it easy to [tailor the recipes](https://docs.moderne.io/user-documentation/moderne-platform/how-to-guides/new-recipe-builder) to your needs with [the builder](https://app.moderne.io/builder), and then share your recipe internally [using our rewrite-recipe-starter](https://github.com/moderneinc/rewrite-recipe-starter). That's a well established pattern that we think works well.

I do understand that it can take some getting used to with the `.formatted()` style, but I do wonder what the problematic cases are that you're referring to. Perhaps we can tweak the recipe not to make any change for convincing cases? That's always our preferred approach.

**Comment by jpraet** [comment]
> Hi @jpraet ; I wouldn't say it's impossible; quite the opposite: we've made it easy to [tailor the recipes](https://docs.moderne.io/user-documentation/moderne-platform/how-to-guides/new-recipe-builder) to your needs with [the builder](https://app.moderne.io/builder), and then share your recipe internally [using our rewrite-recipe-starter](https://github.com/moderneinc/rewrite-recipe-starter). That's a well established pattern that we think works well.

I should have said basically impossible without duplicating the recipe collection and removing the ones I don't want.
Which as I understand it is simplified by the builder, but in the end it's basically still copy/paste right?
If something changes to the upstream recipe collection I copied, my "fork" of that recipe will not be updated?

An example of what throws me off in the `.formatted()` style is when it needs to add parenthesis around a concatenated string.

![image](https://github.com/user-attachments/assets/33547314-54ad-4783-ac99-a932d20f2b4d)

![image](https://github.com/user-attachments/assets/3095374e-17ec-44bc-a79d-ea8fcf8587b6)

More generally to me this feels out of scope of a general purpose "Upgrade to JDK17" recipe, as it is a stylistic change with no other driving force behind it like deprecation or a clear guideline.

https://github.com/openrewrite/rewrite-migrate-java/blob/05b826493ea9a0c2521fd8f05433f6c3331b8844/src/main/resources/META-INF/rewrite/java-version-17.yml#L20-L25

Anyway, I guess it's a matter of preference. I just wanted to open this discussion.

**Comment by timtebeek** [comment]
And know that you feedback is appreciated; we won't always agree on preferences, but where possible we do try to strike that right balance. We've gone through similar changes before with the introduction of text blocks, and I've copied that approach here.

More generally: from time to time we get requests to minimize the changes made by recipes. Some folks would similarly only want to be runtime compatible with Java 21 for instance, and forego the SequencedCollection recipes that introduce `getFirst()` and `getLast()`. We think including those changes helps the code quality overall; and the builder is then a way for folks to diverge when they want to.

Your case above was convincing enough to make changes; if you have any more feel free to raise those here, or in a draft unit test to explain what you're after.

**Comment by canthonyparkinson** [comment]
I have just discovered the whole Open Rewrite project.  I want to add my support for not including StringFormatted in  UpgradeToJava17.  For new users, the process of duplicating and removing it can be a bit daunting, and it would be much easier for anyone who wants it to just add one more recipe.  The problem is exacerbated when the user is not just doing UpgradeToJava17 but perhaps UpgradeSpringBoot_3_0 which contains UpgradeToJava17 so you need to duplicate both of these.

Another objection to StringFormatted  is that it can introduce massive change into a code base perhaps thousands of lines over hundreds of classes which can cause an issue of GIT conflicts, all over what I completely agree is a "stylistic change".

**Comment by timtebeek** [comment]
Hi! Thanks for finding an appropriate place to comment rather than start a new issue. We've recently added a set of more opinionated Java best practices recipes to hold the ones we recommend, but where not necessarily everyone agrees. I've just pushed a change to move the String.formatted recipe there, such that folks can consciously opt in
- https://github.com/openrewrite/rewrite-migrate-java/pull/1106

**Comment by canthonyparkinson** [comment]
Thanks for the update.  Is this change in an official release yet and if so, what version.

**Comment by timtebeek** [comment]
Hi! This has not yet made it into a release; that's expected in roughly two weeks. Until then you can use [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions).

**Comment by canthonyparkinson** [comment]
What SNAPSHOT version should I use ?
