### ISSUE TITLE
Can't build because of license headers

### ISSUE THREAD

**Issue by timo-a** [openrewrite/rewrite-migrate-java#627]
Since today I can no longer build this repo with `./gradlew build`
relevant log:
```
* What went wrong:
Execution failed for task ':licenseMain'.
> License violations were found: <list of all(?) recipes in the repo>
```

I believe this is tied to https://github.com/openrewrite/rewrite-build-gradle-plugin/releases/tag/v1.19.0 and virtually all license headers in this repo need to be fixed.

Setting the dependency version back like this is 
```
plugins {
    id("org.openrewrite.build.recipe-library") version "1.18.0"
}
```
fixes the build.

This is the second time this has happened to me. I think having `latest.release` in the build.gradle is dangerous. I would recommend having explicit versions in the build.gradle and updating them via e.g. [renovate](https://docs.renovatebot.com/). This way, you can be sure that a commit that built yesterday still builds today.

**Comment by timtebeek** [comment]
Hi @timo-a indeed we had found the same. Thanks for logging an issue to keep track. Indeed you can pin the older version for now. We'll also come through with a proper fix within the next few days

**Comment by jkschneider** [comment]
We are trying to fix license headers throughout the org, so the change was intentional and instead of rolling back the build tooling we will be fixing the headers.
