### ISSUE TITLE
Recipe to transform uses of Collections.unmodifiableXX to Immutable Static Factory Methods

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#67]
I believe that this belongs here (otherwise please let me know under what module this should be reported) 

it would be nice to add a rule to the Java 8 -> Java 11 migration to apply the following transformation : 

Before : 

`Set<String> s = Collections.unmodifiableSet(new HashSet<>(Arrays.asList("A", "B")));
`

After 

`Set<String> s = Set.of("A", "B")`

Additional resources : 

See : https://docs.oracle.com/en/java/javase/11/core/creating-immutable-lists-sets-and-maps.html#GUID-930A5334-9413-4E87-A1D7-6FF4E9E421B2

**Comment by traceyyoshima** [comment]
Posterity:
https://github.com/openrewrite/rewrite-migrate-java/issues/67#issuecomment-1082488554
https://github.com/openrewrite/rewrite-migrate-java/issues/67#issuecomment-1082488556

**Comment by tkvangorder** [comment]
@yeikel This is a very good suggestion.

**Comment by traceyyoshima** [comment]
@yeikel I added the base recipes for the examples you provided in this [commit](https://github.com/openrewrite/rewrite-migrate-java/commit/225349a28b934839f8c53d2247d71558be6fa4b5).

I decided not to handle situations like:

**Before**
```java
List<String> stringList = Arrays.asList("a", "b", "c");
stringList = Collections.unmodifiableList(stringList);
```
**After**
```java
List<String> stringList = List.of("a", "b", "c");
```
Because it would require removing a statement and there could be relevant code in between lines 1 and 2, a multi-variable declaration, etc.

Dataflow analysis is in development and we'll be able to handle the transformation safely once it's finished.

Thanks again for the suggestion!

**Comment by yeikel** [comment]
> @yeikel I added the base recipes for the examples you provided in this [commit](https://github.com/openrewrite/rewrite-migrate-java/commit/225349a28b934839f8c53d2247d71558be6fa4b5).
> 
> I decided not to handle situations like:
> 
> **Before**
> ```java
> List<String> stringList = Arrays.asList("a", "b", "c");
> stringList = Collections.unmodifiableList(stringList);
> ```
> **After**
> ```java
> List<String> stringList = List.of("a", "b", "c");
> ```
> Because it would require removing a statement and there could be relevant code in between lines 1 and 2, a multi-variable declaration, etc.
> 
> Dataflow analysis is in development and we'll be able to handle the transformation safely once it's finished.
> 
> Thanks again for the suggestion!

Thar makes sense. Thank you for explaining!

**Comment by yeikel** [comment]
@traceyyoshima 

While testing my changes for #80 

I found that the following condition not covered by your implemention 

```java
@Issue("https://github.com/openrewrite/rewrite-migrate-java/issues/67")
@Test
    fun unmodifiableSetTyped() = assertChanged(
        before = """
            import java.util.*;
            import java.time.LocalDate;
            
            class Test {
                Set<Integer> s = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(LocalDate.of(2010,1,1),LocalDate.now())));
            }
        """,
        after = """
            import java.util.Set;
            import java.time.chrono.ChronoLocalDate;
            
            class Test {
                Set<LocalDate> s = Set.of(LocalDate.of(2010,1,1),LocalDate.now());
            }
        """
    )
```

I tried fixing it myself, but I am not sure how the `MethodMatcher` should look like in this case

**Comment by traceyyoshima** [comment]
@yeikel  thanks for letting me know. I'll take a look first thing on Monday :)

**Comment by yeikel** [comment]
@traceyyoshima Did you get a chance to take a look at this? I noticed it was released today without the fix :(

**Comment by traceyyoshima** [comment]
Hi @yeikel!

Apologies, not yet. I'm working on a few things related to the release and haven't had time yet.

But I know what the issue is:
- The method arguments in the template need to be updated from `#{}` to `#{any()}` to allow types.
- The test needs to be updated from `Set<Integer>` to `Set<LocalDate>`.

:)

**Comment by traceyyoshima** [comment]
@yeikel just pushed the update. Thanks again!

**Comment by yeikel** [comment]
> @yeikel just pushed the update. Thanks again!

Thank you!
