### ISSUE TITLE
Recipe for java:S3599 : Double Brace Initialization should not be used

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#69]
```
Map<String,String> source = new HashMap(){{ 
    put("firstName", "John");
    put("lastName", "Smith");
}};
```

Java 8 compliant : 

```
Map<String,String> source = new HashMap();
source.put("firstName", "John");
source.put("lastName", "Smith");

```

Java 11 compliant (immutable) : 

```
Map<String,String> source = Map.of("firstName", "John","lastName", "Smith");
```

More context : https://rules.sonarsource.com/java/RSPEC-3599

**Comment by pway99** [comment]
Good Morning @yeikel :)
Both of these conversions should be accounted for:

https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoDoubleBraceInitialization.java

https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/lang/UseMapOf.java

**Comment by yeikel** [comment]
> https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoDoubleBraceInitialization.java

That's awesome. Thank you! 


Unfortunately, it seems that this doc is outdated : https://docs.openrewrite.org/reference/recipes/java/cleanup/cleanup 

I was able to find that rule in the sidebar but not in the main recipe list 

![image](https://user-images.githubusercontent.com/8935151/160876862-68f75e9a-9671-45fc-a7db-bf714d1708ad.png)

**Comment by pway99** [comment]
sure there are a lot of recipes to look through and not all of them are included in the cleanup or static-code-analysis recipes.  🤔  `NoDoubleBraceInitialization` may be a good `Cleanup` recipe candidate.
