### ISSUE TITLE
Recipe to Migrate Deprecated `java.net` APIs

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#7]
- [ ] `void java.net.DatagramSocketImpl.setTTL()` -> `setTimeToLive` (ag, skip)
- [ ] `byte java.net.DatagramSocketImpl.getTTL()` -> `setTimeToLive` (ag, skip)
- [x] `void java.net.MulticastSocket.setTTL()` -> `setTimeToLive`
- [x] `byte java.net.MulticastSocket.getTTL()` -> `getTimeToLive`
- [ ] `void java.net.MulticastSocket.send()` -> See notes in JavaDocs
- [x] `java.net.HttpURLConnection.HTTP_SERVER_ERROR` -> `HTTP_INTERNAL_ERROR`
- [ ] `java.net.Socket(String,int,boolean)` -> `DatagramSocket` constructor
- [ ] `java.net.Socket(java.net.InetAddress,int,boolean)` -> `DatagramSocket` constructor
- [ ] `void java.net.URLConnection.setDefaultRequestProperty()` -> See notes in JavaDocs
- [ ] `java.lang.String java.net.URLConnection.getDefaultRequestProperty()` -> See notes in JavaDocs
- [x] `java.lang.String java.net.URLDecoder.decode()` -> See notes in JavaDocs
- [x] `java.lang.String java.net.URLEncoder.encode()` -> See notes in JavaDocs
- [ ] `void java.net.URLStreamHandler.setURL ()` -> See notes in JavaDocs

**Comment by aegershman** [comment]
Closing, we can revisit some of these more involved deprecations if there is a high demand for this at a later date 👍
