### ISSUE TITLE
Replace Collections.singletonXXX with Immutable Static Factory Methods

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#72]
This is similar to https://github.com/openrewrite/rewrite-migrate-java/issues/67

Replace 

```java

List<String> list = Collections.singletonList("E")
Map<String,String> map = Collections.singletonMap("field3", "value3");
Set<String> set = Collections.singleton("Hello");



```

With 

```java
List<String> list =  List.of("e")
Map<String,String> map = Map.of"field3", "value3");
Set<String> set  = Set.of("Hello");

```

**Comment by tkvangorder** [comment]
@traceyyoshima Didn't you recently do this work?

**Comment by yeikel** [comment]
> Hi @yeikel, thanks for reporting the issue!
> 
> I think this would be a great first issue for anyone who'd like to get their feet wet with writing recipes. The recipes to migrate singleton List, Map, Set would be nearly identical to `Collections.unmodifiableX`. Links to [set](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/lang/MigrateCollectionsUnmodifiableSet.java) and [list](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/lang/MigrateCollectionsUnmodifiableList.java).
> 
> The difference would be in the `MethodMatchers` I.E. `java.util.Collections unmodifiableSet(java.util.Set)` would check for singletonList instead. :)
> 
> `singletonMap` looks safe as well if it's scoped to your example. I'm happy to help if you have any questions or need any support along the way.
> 
> 

Definitely. I can give it a try

**Comment by yeikel** [comment]
@traceyyoshima 

While testing my changes for #80 

I found the following condition not convered by your implemention 

```java
@Issue("https://github.com/openrewrite/rewrite-migrate-java/issues/67")
    @Test
    fun unmodifiableSetTyped() = assertChanged(
        before = """
            import java.util.*;
            import java.time.LocalDate;
            
            class Test {
                Set<Integer> s = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(LocalDate.of(2010,1,1),LocalDate.now())));
            }
        """,
        after = """
            import java.util.Set;
            import java.time.chrono.ChronoLocalDate;
            
            class Test {
                Set<LocalDate> s = Set.of(LocalDate.of(2010,1,1),LocalDate.now());
            }
        """
    )
```

I tried fixing it initially, but I am not sure how the `MethodMatcher` should look like in this case
