### ISSUE TITLE
Provide recipe to upgrade `wro4j` to a version that is compatible with Java 11

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#75]
Need to look at the release notes for `wro4j` to determine which version should be used with Java 11.

See: 

https://stackoverflow.com/a/62362986
https://blog.jdriven.com/2022/03/major-migrations-made-easy-with-openrewrite/

**Comment by timtebeek** [comment]
It appears the minimum version is [1.9.0](https://github.com/wro4j/wro4j/releases/tag/v1.9.0):
> Now built against OpenJDK 9, 10 & 11

With the most recent version (November 2020) being [1.10.1](https://github.com/wro4j/wro4j/releases/tag/v1.10.1).

There does not appear to have been much (if any) activity after 1.10.1, so bumping to that version could be enough for the foreseeable future.
