### ISSUE TITLE
Java 15+ recipe to adopt non-static String formatted(Object... args)

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-migrate-java#77]
As of [Java 15 JEP 378: Text Blocks](https://openjdk.java.net/jeps/378) there's a new [`String formatted(Object... args)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#formatted(java.lang.Object...)) that's equivalent to `String.format(this, args)`. It reads quite nicely even when not used with text blocks.

I have no idea if you're already taking in suggestions beyond Java 11, but figured this could be a nice addition.

**Comment by tkvangorder** [comment]
Support for later versions of Java is high on our priority list. This is a good suggestion.

**Comment by timtebeek** [comment]
Perfect; cross referencing [Java 17 parser support](https://github.com/openrewrite/rewrite/issues/1501) here. Perhaps a new label could help group the issues here, as I imagine there's further quality of life suggestions that aren't actionable yet, such as text blocks, instance of test & assignment, and switch expressions.

**Comment by Jonpez2** [comment]
I’d be really interested to learn more about your plans for later versions of Java. Is there anywhere I could read about it please?

Thank you!
