### ISSUE TITLE
Recipe to Migrate Deprecated Sax APIs

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#8]
The following four interfaces/classes have been deprecated in favor of their Sax 2.0 counterparts. This recipe should migrate the use of these to the Sax 2.0 API. We should first evaluate if this work is worth the time and effort. 

- [ ] `interface org.xml.sax.AttributeList` // This was can be done pretty safely, but it's a matter of if it's worth the time. There are no breaking changes between the APIs, but the recipe would need to override and stub out methods that were added in each implementation.
- [ ] `interface org.xml.sax.DocumentHandler` // Includes a breaking change in startElement(String, AttributeList) => startElement(String, String, String, Attributes).
- [ ] `class org.xml.sax.HandlerBase` // Includes tricky changes from DocumentHandler. HandlerBase implements DocumentHandler and is replaced by DefaultHandler that implements DocumentHandler.
- [ ] `interface org.xml.sax.Parser` // Doesn't look possible through a recipe. The Parser interface was replaced by XMLReader, which is very different.
- [ ] `org.xml.sax.helpers.AttributeListImpl` // Not possible.
- [ ] `org.xml.sax.helpers.ParserFactory` // Not possible.
- [ ] `org.xml.sax.helpers.XMLReaderFactory` // Doesn't look possible; method names, arguments, and return types were changes.

**Comment by traceyyoshima** [comment]
Most of the deprecations aren't possible through general recipes - the change require internal knowledge of how the interfaces are implemented.
One of the items in the list is _doable_, but would take a bit of time.
Closing until there is a known need for the work.
