### ISSUE TITLE
Recipe to Migrate Deprecated `javax.xml` APIs

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#9]
- [x] `javax.xml.stream.XMLEventFactory.newInstance()` -> newFactory()
- [x] `javax.xml.stream.XMLInputFactory.newInstance()` -> newFactory()
- [x] `javax.xml.stream.XMLOutputFactory.newInstance()` -> newFactory()

**Comment by traceyyoshima** [comment]
The commit has a comment with a tag to this issue, but it didn't close.
Fixed in [commit](https://github.com/openrewrite/rewrite-migrate-java/commit/b6ba7387676babe483e979d87d39dba5029db682).

**Comment by tkvangorder** [comment]
@traceyyoshima The deprecations on newInstance() are actually on the two-argument variant and those are the ones that are deprecated.

**Comment by tkvangorder** [comment]
Fixed with #https://github.com/openrewrite/rewrite-migrate-java/commit/53fcb4e9c8232257b10c22d77b1afd43f66607b1
