### ISSUE TITLE
bug: ApacheBase64ToJavaBase64 does not transform Base64.encodeBase64URLSafeString

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#90]
Leaving   the import `import org.apache.commons.codec.binary.Base64` leads to a conflict with `import java.util.Base64` and a compiler error

![image](https://user-images.githubusercontent.com/8935151/163509454-619d4fd1-a877-406b-bbd1-b82e7137c945.png)

It also does not transform `Base64.encodeBase64URLSafeString`

From what I understand and tested, the closest to that is `Base64.getUrlEncoder().withoutPadding().encodeToString`

Sample class to reproduce this problem : 

```java

import org.apache.commons.codec.binary.Base64;

import javax.crypto.Mac;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

public class TokenGenerator {

    private String generateSignature(final String appId, final String secret, final String version, final long timestamp) throws NoSuchAlgorithmException, InvalidKeyException {
        final Mac mac = Mac.getInstance("HmacSHA256");
        final byte[] hmacKeyBytes = Base64.decodeBase64(secret.getBytes());
        final SecretKey secretKey = new SecretKeySpec(hmacKeyBytes, mac.getAlgorithm());
        mac.init(secretKey);
        final String input = appId + "-" + version + "-" + timestamp;
        final byte[] rawHmac = mac.doFinal(input.getBytes());
        return Base64.encodeBase64URLSafeString(rawHmac);
    }
}

```

command I executed : 

`mvn rewrite:run -Drewrite.activeRecipes="org.openrewrite.java.migrate.apache.commons.codec.ApacheBase64ToJavaBase64"`

diff : 

```diff
@@ -16,6 +16,7 @@ import java.net.URI;
 import java.net.URISyntaxException;
 import java.security.InvalidKeyException;
 import java.security.NoSuchAlgorithmException;
+import java.util.Base64;
 import java.util.HashMap;
 import java.util.Map;
 import java.util.concurrent.TimeUnit;
@@ -111,7 +112,7 @@ public class TokenGenerator {
 
     private String generateSignature(final String appId, final String secret, final String version, final long timestamp) throws NoSuchAlgorithmException, InvalidKeyException {
         final Mac mac = Mac.getInstance("HmacSHA256");
-        final byte[] hmacKeyBytes = Base64.decodeBase64(secret.getBytes());
+        final byte[] hmacKeyBytes = Base64.getDecoder().decode(secret.getBytes());
         final SecretKey secretKey = new SecretKeySpec(hmacKeyBytes, mac.getAlgorithm());
         mac.init(secretKey);
         final String input = appId + "-" + version + "-" + timestamp;




```

Expected : 

```java

private String generateSignature(final String appId, final String secret, final String version, final long timestamp) throws NoSuchAlgorithmException, InvalidKeyException {
        final Mac mac = Mac.getInstance("HmacSHA256");
        final byte[] hmacKeyBytes = Base64.getDecoder().decode(secret.getBytes());
        final SecretKey secretKey = new SecretKeySpec(hmacKeyBytes, mac.getAlgorithm());
        mac.init(secretKey);
        final String input = appId + "-" + version + "-" + timestamp;
        final byte[] rawHmac = mac.doFinal(input.getBytes());
        return Base64.getUrlEncoder().withoutPadding().encodeToString(rawHmac);
    }


```

**Comment by pway99** [comment]
Thanks Yiekel,

> From what I understand and tested, the closest to that is Base64.getUrlEncoder().withoutPadding().encodeToString

 I recall being uncertain with that conversion and most likely chose not to migrate those statements.  If we can prove the results are exactly the same then I would not hesitate to update the recipe accordingly.  

This is an excellent example of intentionally not converting a statement in the spirit of `do no harm`.  Consider a case where the encoding is not precisely the same after the conversion; the app is deployed to production, and every request associated with the encoding process fails.

**Comment by yeikel** [comment]
I understand your point, but if we can't do a full conversion, shouldn't we just don't proceed at all and print a warning?

Leaving a broken build is not acceptable in my opinion

**Comment by pway99** [comment]
Good point. It would be easy to skip the SourceFile if that method exists or add a comment as you suggest.  I will make that update now. Thanks for the suggestion

**Comment by tkvangorder** [comment]
We definitely should not be leaving a source file in a broken state.

**Comment by pway99** [comment]
Hi @yeikel, Looking at the code and running a few tests it appears to be a safe conversion.  I will update the recipe. 

apache commons
https://github.com/apache/commons-codec/blob/5f90731d40e6ed12d1ebfddfeb5dca5550d19cdd/src/main/java/org/apache/commons/codec/binary/Base64.java#L207-L209

java util
https://github.com/apache/commons-codec/blob/5f90731d40e6ed12d1ebfddfeb5dca5550d19cdd/src/main/java/org/apache/commons/codec/binary/Base64.java#L207-L209

Thanks again for the suggestion :)
