### ISSUE TITLE
Java 14+ : add `@Serial` annotation to `serialVersionUID` fields

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#96]
Relevant : 
https://mail.openjdk.java.net/pipermail/core-libs-dev/2021-September/081364.html
https://stackoverflow.com/questions/63783474/what-is-the-use-of-serial-annotation-as-of-java-14

**Comment by melloware** [comment]
+1 for this. Dont know how easy this would be though.

**Comment by melloware** [comment]
@timtebeek i am interested in doing this one but need a hint on how to get started.  The general idea is

1. detect `private static final long serialVersionUID = 1L;`
2. Add `  maybeAddImport("java.io.Serial", false);`
3. Add `@Serial` above the `private static final long serialVersionUID`

**Comment by timtebeek** [comment]
hi @melloware, welcome back! It seems this open issue was missed when the recipe was implemented in ~another castle~ rewrite-static-analysis
- https://github.com/openrewrite/rewrite-static-analysis/pull/247

You can already use that existing recipe; I've just pushed up a change to the latest snapshot to correct the casing:
- https://github.com/openrewrite/rewrite-static-analysis/commit/6ccce06eec50260005bc08fcdc09bb8fddc46216

Thanks for reaching out on this issue! Good to see this can be closed.

**Comment by melloware** [comment]
OK wasn't sure where to ask but I wasn't seeing this run as part of a Java 17 migration i just did so I assumed this would have been part of an automatic upgrade recipe?

**Comment by timtebeek** [comment]
I had doubted at the time to make this part of the upgrade recipe; the way I see it there might be some push back from folks that prefer a "minimal" migration, as opposed to having to review additional lines any place there's a `serialVersionUID`. What would be your argument for inclusion by default? Just to weigh the options.

**Comment by melloware** [comment]
Yeah I guess my only argument is in INtelliJ when I open a Java 17 or 21 project that warning comes up on every class to add `@Serial` so its one less thing I have to do to N classes on a Migration.  That was my only thought.  

In theory I can run the 17 Recipe and then run this custom recipe.  But there is a reason Java added this and to me it make sense to migrate it by default.  Just my two cents.

**Comment by timtebeek** [comment]
Ah I didn't know about the warnings in IntelliJ IDEA; that'd be a stronger reason to include this recipe by default. Would you want to push that up?

**Comment by melloware** [comment]
Yes let me submit a PR.
